-- generated by newgenasym Thu Feb 11 00:01:07 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end conn3;
