// generated by newgenasym  Sun Apr 23 14:29:34 2006


module lm340 (\1 , \2 , \3 , \4 );
    input \1 ;
    input \2 ;
    output \3 ;
    input \4 ;


    initial
        begin
        end

endmodule
