-- generated by newgenasym Sat Mar 11 10:13:25 2000

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74ac00\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \74ac00\;
