// generated by newgenasym  Wed Aug 08 15:32:56 2012


module lm1085 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
