-- generated by newgenasym Sun Mar 30 00:51:46 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc08\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74hc08\;
