// generated by newgenasym  Tue Jun 17 15:55:12 2014


module sy89828 (clk_sel1, clk_sel2, gndi, gndo1, gndo2, gndpad1, gndpad2,
        gndpad3, gndpad4, gndpad5, gndpad6, gndpad7, gndpad8,
        gndpad9, \lvds_clka+ , \lvds_clka- , \lvds_clkb+ , \lvds_clkb- ,
        \lvpecl_clka+ , \lvpecl_clka- , \lvpecl_clkb+ , \lvpecl_clkb- ,
        oe1, oe2, \q0+ , \q0- , \q1+ , \q1- , \q10+ , \q10- , \q11+ , \q11- , \q12+ , \q12- ,
        \q13+ , \q13- , \q14+ , \q14- , \q15+ , \q15- , \q16+ , \q16- , \q17+ , \q17- ,
        \q18+ , \q18- , \q19+ , \q19- , \q2+ , \q2- , \q3+ , \q3- , \q4+ , \q4- , \q5+ , \q5- ,
        \q6+ , \q6- , \q7+ , \q7- , \q8+ , \q8- , \q9+ , \q9- , sel1, sel2, vcci, vcco1,
        vcco2, vcco3, vcco4, vcco5, vcco6);
    input clk_sel1;
    input clk_sel2;
    input gndi;
    input gndo1;
    input gndo2;
    input gndpad1;
    input gndpad2;
    input gndpad3;
    input gndpad4;
    input gndpad5;
    input gndpad6;
    input gndpad7;
    input gndpad8;
    input gndpad9;
    input \lvds_clka+ ;
    input \lvds_clka- ;
    input \lvds_clkb+ ;
    input \lvds_clkb- ;
    input \lvpecl_clka+ ;
    input \lvpecl_clka- ;
    input \lvpecl_clkb+ ;
    input \lvpecl_clkb- ;
    input oe1;
    input oe2;
    output \q0+ ;
    output \q0- ;
    output \q1+ ;
    output \q1- ;
    output \q10+ ;
    output \q10- ;
    output \q11+ ;
    output \q11- ;
    output \q12+ ;
    output \q12- ;
    output \q13+ ;
    output \q13- ;
    output \q14+ ;
    output \q14- ;
    output \q15+ ;
    output \q15- ;
    output \q16+ ;
    output \q16- ;
    output \q17+ ;
    output \q17- ;
    output \q18+ ;
    output \q18- ;
    output \q19+ ;
    output \q19- ;
    output \q2+ ;
    output \q2- ;
    output \q3+ ;
    output \q3- ;
    output \q4+ ;
    output \q4- ;
    output \q5+ ;
    output \q5- ;
    output \q6+ ;
    output \q6- ;
    output \q7+ ;
    output \q7- ;
    output \q8+ ;
    output \q8- ;
    output \q9+ ;
    output \q9- ;
    input sel1;
    input sel2;
    input vcci;
    input vcco1;
    input vcco2;
    input vcco3;
    input vcco4;
    input vcco5;
    input vcco6;


    initial
        begin
        end

endmodule
