-- generated by newgenasym Tue Oct 16 12:25:53 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \8pindipclock\ is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       OUT    STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end \8pindipclock\;
