// generated by newgenasym  Wed Oct 03 23:05:26 2012


module samtec_asp_134602_01 (a, b, c, d, e, f, g, h, j, k);
    inout [40:1] a;
    inout [40:1] b;
    inout [40:1] c;
    inout [40:1] d;
    inout [40:1] e;
    inout [40:1] f;
    inout [40:1] g;
    inout [40:1] h;
    inout [40:1] j;
    inout [40:1] k;


    initial
        begin
        end

endmodule
