// generated by newgenasym  Fri Dec  4 11:28:59 2009


module mitch_fanout_5 (in, out1, out2, out3, out4, out5);
    inout in;
    inout out1;
    inout out2;
    inout out3;
    inout out4;
    inout out5;


    initial
        begin
        end

endmodule
