// generated by newgenasym  Thu May 31 17:00:01 2012


module opa2835 (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;
    input \7 ;
    input \8 ;
    output \9 ;


    initial
        begin
        end

endmodule
