-- generated by newgenasym Thu May 31 17:00:01 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa2835 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       OUT    STD_LOGIC);
end opa2835;
