-- generated by newgenasym Thu Dec 20 18:35:02 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bzt52h is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end bzt52h;
