-- generated by newgenasym Tue Oct 09 14:33:33 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity kc2520c_clock_driver is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       OUT    STD_LOGIC);
end kc2520c_clock_driver;
