// generated by newgenasym  Tue Oct 09 14:33:33 2012


module kc2520c_clock_driver (\1 , \2 , \3 , \4 );
    input \1 ;
    input \2 ;
    input \3 ;
    output \4 ;


    initial
        begin
        end

endmodule
