// generated by newgenasym  Mon Feb 13 13:29:35 2012


module hv_conn3 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
