-- generated by newgenasym Fri Feb 24 13:27:47 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hdr2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end hdr2;
