// generated by newgenasym  Tue Jan 22 14:09:20 2013


module hfa1135 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    inout \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    output \6 ;
    input \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
