-- generated by newgenasym Tue Mar 26 15:43:04 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tc59 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end tc59;
