// generated by newgenasym  Thu Jan  6 12:35:51 2011


module pwrjack (\1 , \2 , \3 , \4 );
    input \1 ;
    input \2 ;
    input \3 ;
    input \4 ;


    initial
        begin
        end

endmodule
