-- generated by newgenasym Thu Jan  6 12:35:51 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pwrjack is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC);
end pwrjack;
