// generated by newgenasym  Fri Mar 31 11:10:34 2006


module ds26ls32 (\1a , \1b , \1y , \2a , \2b , \2y , \3a , \3b , \3y , \4a , \4b , \4y , g, \g* , gnd, vcc);
    input \1a ;
    input \1b ;
    output \1y ;
    input \2a ;
    input \2b ;
    output \2y ;
    input \3a ;
    input \3b ;
    output \3y ;
    input \4a ;
    input \4b ;
    output \4y ;
    input g;
    input \g* ;
    input gnd;
    input vcc;


    initial
        begin
        end

endmodule
