-- generated by newgenasym Thu Sep 12 15:49:56 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPA548 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC);
end OPA548;
