-- generated by newgenasym Wed Sep 17 11:16:50 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity srr6038 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end srr6038;
