// generated by newgenasym  Wed Jan 04 15:14:56 2017


module ltc2050 (\in+ , \in- , out, \v+ , \v- );
    inout \in+ ;
    inout \in- ;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
