-- generated by newgenasym Wed Jan 04 15:14:56 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ltc2050 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end ltc2050;
