-- generated by newgenasym Fri May 14 12:36:00 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad5308 is
    port (    
	DIN:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	LDAC_N:    IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	SYNC_N:    IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VOUTA:     INOUT  STD_LOGIC;    
	VOUTB:     INOUT  STD_LOGIC;    
	VOUTC:     INOUT  STD_LOGIC;    
	VOUTD:     INOUT  STD_LOGIC;    
	VOUTE:     INOUT  STD_LOGIC;    
	VOUTF:     INOUT  STD_LOGIC;    
	VOUTG:     INOUT  STD_LOGIC;    
	VOUTH:     INOUT  STD_LOGIC;    
	VREFABCD:  INOUT  STD_LOGIC;    
	VREFEFGH:  INOUT  STD_LOGIC);
end ad5308;
