-- generated by newgenasym Tue Mar 26 18:25:37 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BAS40_04_SERIAL is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end BAS40_04_SERIAL;
