-- generated by newgenasym Tue Aug 24 10:55:16 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_b is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cap_b;
