-- generated by newgenasym Fri Mar 24 19:18:31 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end conn4;
