// generated by newgenasym  Fri Oct 26 12:34:00 2012


module opa2836 (\1 , \10 , \2 , \3 , \4 , \5 );
    input \1 ;
    input \10 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;


    initial
        begin
        end

endmodule
