// generated by newgenasym  Wed Apr 01 15:55:17 2009


module \ada4937-1  (\+fb , \+in , \+out , \+v1 , \+v2 , \+v3 , \+v4 , \-fb , \-in , \-out , \-v1 , \-v2 ,
        \-v3 , \-v4 , \pd* , vocm);
    input \+fb ;
    input \+in ;
    output \+out ;
    input \+v1 ;
    input \+v2 ;
    input \+v3 ;
    input \+v4 ;
    input \-fb ;
    input \-in ;
    output \-out ;
    input \-v1 ;
    input \-v2 ;
    input \-v3 ;
    input \-v4 ;
    input \pd* ;
    input vocm;


    initial
        begin
        end

endmodule
