// generated by newgenasym  Fri Dec  4 11:29:38 2009


module mitch_fanout_6 (in, out1, out2, out3, out4, out5, out6);
    inout in;
    inout out1;
    inout out2;
    inout out3;
    inout out4;
    inout out5;
    inout out6;


    initial
        begin
        end

endmodule
