// generated by newgenasym  Tue Nov 20 14:30:13 2012


module sn65lvds117 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 , \25 ,
        \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \39 , \4 , \40 , \41 ,
        \42 , \43 , \44 , \45 , \46 , \47 , \48 , \49 , \5 , \50 , \51 , \52 , \53 , \54 , \55 , \56 , \57 , \58 ,
        \59 , \6 , \60 , \61 , \62 , \63 , \64 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    input \12 ;
    input \13 ;
    input \14 ;
    input \15 ;
    input \16 ;
    input \17 ;
    input \18 ;
    input \19 ;
    input \2 ;
    input \20 ;
    input \21 ;
    inout \22 ;
    input \23 ;
    input \24 ;
    input \25 ;
    input \26 ;
    inout \27 ;
    inout \28 ;
    input \29 ;
    input \3 ;
    input \30 ;
    input \31 ;
    input \32 ;
    output \33 ;
    output \34 ;
    output \35 ;
    output \36 ;
    output \37 ;
    output \38 ;
    output \39 ;
    input \4 ;
    output \40 ;
    output \41 ;
    output \42 ;
    output \43 ;
    output \44 ;
    output \45 ;
    output \46 ;
    output \47 ;
    output \48 ;
    output \49 ;
    inout \5 ;
    output \50 ;
    output \51 ;
    output \52 ;
    output \53 ;
    output \54 ;
    output \55 ;
    output \56 ;
    output \57 ;
    output \58 ;
    output \59 ;
    input \6 ;
    output \60 ;
    output \61 ;
    output \62 ;
    output \63 ;
    output \64 ;
    input \7 ;
    input \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
