-- generated by newgenasym Fri May 30 13:34:24 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps74201 is
    port (    
	BIAS:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC);
end tps74201;
