// generated by newgenasym  Fri Jul 27 15:19:50 2012


module lemo_conn (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
