-- generated by newgenasym Thu Jul 26 14:14:45 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RA_HDR4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end RA_HDR4;
