`timescale 1ns/1ns

module vee ();
// generated by  HDL Direct 15.00-s001 13-Aug-2003
// on Mon Feb  7 17:41:29 2005
// from cnpower/VEE/sch_1

  // global signal glbl.vee;

  wire  vee;
  wire  page1_vee;

  assign vee = glbl.vee;
  assign page1_vee = vee;

// begin instances 

endmodule // vee(sch_1) 
