-- generated by newgenasym Wed May 09 14:16:52 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd0402 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end csmd0402;
