-- generated by newgenasym Wed Oct 24 12:12:09 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5pinx\ is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC);
end \5pinx\;
