-- generated by newgenasym Wed Sep 22 14:42:05 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ssb44_smb is
    port (    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end ssb44_smb;
