-- generated by newgenasym Fri Oct 21 15:18:50 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MMBD1503 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end MMBD1503;
