-- generated by newgenasym Thu Mar 27 22:25:14 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc00\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \74hc00\;
