-- generated by newgenasym Sun Apr 23 14:29:34 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM340 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC);
end LM340;
