// generated by newgenasym  Fri Feb 01 00:13:18 2008


module lm2937_33 (\1 , \2 , \3 , \4 );
    input \1 ;
    input \2 ;
    output \3 ;
    input \4 ;


    initial
        begin
        end

endmodule
