-- generated by newgenasym Fri Feb 01 00:13:18 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM2937_33 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC);
end LM2937_33;
