-- generated by newgenasym Wed Feb 22 13:07:34 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd1206 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd1206;
