-- generated by newgenasym Wed Jun 04 14:21:36 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max6138 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end max6138;
