// generated by newgenasym  Mon Aug  2 15:47:27 2010


module \74f164  (cp, dsa, dsb, \mr* , q);
    input cp;
    input dsa;
    input dsb;
    input \mr* ;
    output [7:0] q;


    initial
        begin
        end

endmodule
