-- generated by newgenasym Thu Jan  6 12:41:41 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bnc is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       IN     STD_LOGIC);
end bnc;
