// generated by newgenasym  Mon Mar 16 15:41:18 2009


module mec8_conn30a (\1 , \11 , \13 , \15 , \17 , \19 , \21 , \23 , \25 , \27 , \29 , \3 , \31 , \33 , \35 , \37 , \39 , \41 ,
        \43 , \45 , \47 , \49 , \5 , \51 , \53 , \55 , \57 , \59 , \7 , \9 );
    inout \1 ;
    inout \11 ;
    inout \13 ;
    inout \15 ;
    inout \17 ;
    inout \19 ;
    inout \21 ;
    inout \23 ;
    inout \25 ;
    inout \27 ;
    inout \29 ;
    inout \3 ;
    inout \31 ;
    inout \33 ;
    inout \35 ;
    inout \37 ;
    inout \39 ;
    inout \41 ;
    inout \43 ;
    inout \45 ;
    inout \47 ;
    inout \49 ;
    inout \5 ;
    inout \51 ;
    inout \53 ;
    inout \55 ;
    inout \57 ;
    inout \59 ;
    inout \7 ;
    inout \9 ;


    initial
        begin
        end

endmodule
