-- generated by newgenasym Tue Aug 26 20:15:52 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ferrite_axial is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ferrite_axial;
