// generated by newgenasym  Wed Apr 01 23:57:56 2009


module lt1369_4x (\+ina , \+inb , \+inc , \+ind , \-ina , \-inb , \-inc , \-ind , outa, outb,
        outc, outd, \v+ , \v- );
    input \+ina ;
    input \+inb ;
    input \+inc ;
    input \+ind ;
    input \-ina ;
    input \-inb ;
    input \-inc ;
    input \-ind ;
    output outa;
    output outb;
    output outc;
    output outd;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
