-- generated by newgenasym Wed Apr 01 23:57:56 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1369_4x is
    port (    
	\+ina\:    IN     STD_LOGIC;    
	\+inb\:    IN     STD_LOGIC;    
	\+inc\:    IN     STD_LOGIC;    
	\+ind\:    IN     STD_LOGIC;    
	\-ina\:    IN     STD_LOGIC;    
	\-inb\:    IN     STD_LOGIC;    
	\-inc\:    IN     STD_LOGIC;    
	\-ind\:    IN     STD_LOGIC;    
	OUTA:      OUT    STD_LOGIC;    
	OUTB:      OUT    STD_LOGIC;    
	OUTC:      OUT    STD_LOGIC;    
	OUTD:      OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end lt1369_4x;
