// generated by newgenasym  Tue Aug 07 10:52:27 2012


module tps731 (en, gnd, in, nr, out);
    inout en;
    inout gnd;
    inout in;
    inout nr;
    inout out;


    initial
        begin
        end

endmodule
