// generated by newgenasym  Wed Mar 02 00:26:30 2016


module bf118w (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
