-- generated by newgenasym Fri Mar 31 10:48:31 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm7805 is
    port (    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end lm7805;
