-- generated by newgenasym Fri Apr 13 17:40:03 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0603 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0603;
