// generated by newgenasym  Thu Jan 12 14:00:36 2006


module max4145 (\in+ , \in- , out, ref, \rg+ , \rg- , sense, vcc, vee);
    inout \in+ ;
    inout \in- ;
    inout out;
    inout ref;
    inout \rg+ ;
    inout \rg- ;
    inout sense;
    input [1:0] vcc;
    input [1:0] vee;


    initial
        begin
        end

endmodule
