-- generated by newgenasym Thu Jan 12 14:00:36 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4145 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	\rg+\:     INOUT  STD_LOGIC;    
	\rg-\:     INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VEE:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0));
end max4145;
