-- generated by newgenasym Tue May 17 12:35:34 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RSMD0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end RSMD0402;
