// generated by newgenasym  Wed Oct 24 12:25:58 2012


module lmh7220 (\1 , \2 , \3 , \4 , \5 , \6 );
    input \1 ;
    input \2 ;
    output \3 ;
    output \4 ;
    input \5 ;
    input \6 ;


    initial
        begin
        end

endmodule
