-- generated by newgenasym Wed Mar 22 18:51:01 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity am26ls32 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	G1:        IN     STD_LOGIC;    
	\g2*\:     IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end am26ls32;
