-- generated by newgenasym Tue Oct 09 13:05:22 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity kc2520c is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC);
end kc2520c;
