-- generated by newgenasym Thu Mar 30 12:22:13 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_0603 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_0603;
