-- generated by newgenasym Thu Jan 05 11:59:47 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bfr182 is
    port (    
	BASE:      INOUT  STD_LOGIC;    
	COLL:      INOUT  STD_LOGIC;    
	EMIT:      INOUT  STD_LOGIC);
end bfr182;
