-- generated by newgenasym Thu Dec 22 16:17:43 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bfr182 is
    port (    
	BASE:      INOUT  STD_LOGIC;    
	COLL:      INOUT  STD_LOGIC;    
	EMIT:      INOUT  STD_LOGIC);
end bfr182;
