-- generated by newgenasym Tue Jan 22 14:09:20 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HFA1135 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       OUT    STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end HFA1135;
