-- generated by newgenasym Mon May 12 13:48:13 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc32\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74hc32\;
