// generated by newgenasym  Fri Nov 19 17:22:06 2004


module powerreglt1185_v2 (fb, ref, vin, vin2, vout);
    output fb;
    inout ref;
    input vin;
    input vin2;
    output vout;


    initial
        begin
        end

endmodule
