-- generated by newgenasym Fri Nov 19 17:22:06 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity POWERREGLT1185_V2 is
    port (    
	FB:        OUT    STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VIN2:      IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end POWERREGLT1185_V2;
