// generated by newgenasym  Mon Jun 02 13:48:30 2014


module max1725 (fb, gnd, in, out, shdn);
    inout fb;
    inout gnd;
    inout in;
    inout out;
    inout shdn;


    initial
        begin
        end

endmodule
