-- generated by newgenasym Mon Jun 02 13:48:30 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max1725 is
    port (    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	SHDN:      INOUT  STD_LOGIC);
end max1725;
