-- generated by newgenasym Tue Aug 07 10:52:27 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps731 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	NR:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end tps731;
