-- generated by newgenasym Fri Sep 14 12:35:27 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mounthole_8mm is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end mounthole_8mm;
