// generated by newgenasym  Tue Oct 02 16:40:52 2012


module j0011d21bnl (ctrx, cttx, ganode, gcathode, \rd+ , \rd- , \td+ , \td- , term1,
        term2, yanode, ycathode);
    inout ctrx;
    inout cttx;
    inout ganode;
    inout gcathode;
    inout \rd+ ;
    inout \rd- ;
    inout \td+ ;
    inout \td- ;
    inout term1;
    inout term2;
    inout yanode;
    inout ycathode;


    initial
        begin
        end

endmodule
