-- generated by newgenasym Mon May 12 12:35:29 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc1g32\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end \74lvc1g32\;
