-- generated by newgenasym Thu Oct 25 13:06:38 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPA2836_SINGLE is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC);
end OPA2836_SINGLE;
