-- generated by newgenasym Wed Jan 27 21:19:55 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bat54wx is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end bat54wx;
