// generated by newgenasym  Wed May 14 16:14:09 2014


module max15066 (a1, a2, a3, a4, b1, b2, b3, b4, c1, c2, c3, c4, d1, d2, d3, d4);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout c1;
    inout c2;
    inout c3;
    inout c4;
    inout d1;
    inout d2;
    inout d3;
    inout d4;


    initial
        begin
        end

endmodule
