-- generated by newgenasym Fri Mar 02 14:36:48 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity Q2N4624B is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end Q2N4624B;
