// generated by newgenasym  Thu Mar 27 15:17:50 2014


module \10h125  (a, \b* , v, y);
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output v;
    output [size-1:0] y;


    initial
        begin
        end

endmodule
