// generated by newgenasym  Wed Jan 27 19:02:43 2016


module sn74auc1g02 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
