-- generated by newgenasym Wed Jan 27 19:02:43 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74auc1g02 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end sn74auc1g02;
