-- generated by newgenasym Tue Oct 02 12:06:20 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity test_point is
    port (    
	\1\:       INOUT  STD_LOGIC);
end test_point;
