// generated by newgenasym  Mon Jul 07 13:35:06 2014


module ths4521_new (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    input \1 ;
    input \2 ;
    input \3 ;
    output \4 ;
    output \5 ;
    input \6 ;
    input \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
