-- generated by newgenasym Mon Jul 07 13:35:06 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths4521_new is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       OUT    STD_LOGIC;    
	\5\:       OUT    STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end ths4521_new;
