// generated by newgenasym  Wed Mar 25 00:46:16 2009


module ad9245 (\1#20dnc , \15#20dgnd , \2#20clk , \22#20mode , \23#20sense , \28#20agnd , \29#20vin+ ,
        \3#20dnc , \30#20vin- , \31#20agnd , \33#20gnd , \4#20pdwn , \avdd#2027 , \avdd#2032 ,
        \d0#205 , \d1#206 , \d10#2017 , \d11#2018 , \d12#2019 , \d13#2020 , \d2#207 , \d3#208 , \d4#209 ,
        \d5#2010 , \d6#2011 , \d7#2012 , \d8#2013 , \d9#2014 , \drvdd#2016 , \otr#2021 ,
        \refb-#2025 , \reft-#2026 , \vref#2024 );
    input \1#20dnc ;
    input \15#20dgnd ;
    input \2#20clk ;
    input \22#20mode ;
    input \23#20sense ;
    input \28#20agnd ;
    input \29#20vin+ ;
    inout \3#20dnc ;
    input \30#20vin- ;
    input \31#20agnd ;
    input \33#20gnd ;
    input \4#20pdwn ;
    input \avdd#2027 ;
    input \avdd#2032 ;
    output \d0#205 ;
    output \d1#206 ;
    output \d10#2017 ;
    output \d11#2018 ;
    output \d12#2019 ;
    output \d13#2020 ;
    output \d2#207 ;
    output \d3#208 ;
    output \d4#209 ;
    output \d5#2010 ;
    output \d6#2011 ;
    output \d7#2012 ;
    output \d8#2013 ;
    output \d9#2014 ;
    input \drvdd#2016 ;
    output \otr#2021 ;
    input \refb-#2025 ;
    input \reft-#2026 ;
    input \vref#2024 ;


    initial
        begin
        end

endmodule
