-- generated by newgenasym Wed Mar 25 00:46:16 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD9245 is
    port (    
	\1 dnc\:   IN     STD_LOGIC;    
	\15 dgnd\: IN     STD_LOGIC;    
	\2 clk\:   IN     STD_LOGIC;    
	\22 mode\: IN     STD_LOGIC;    
	\23 sense\: IN     STD_LOGIC;    
	\28 agnd\: IN     STD_LOGIC;    
	\29 vin+\: IN     STD_LOGIC;    
	\3 dnc\:   INOUT  STD_LOGIC;    
	\30 vin-\: IN     STD_LOGIC;    
	\31 agnd\: IN     STD_LOGIC;    
	\33 gnd\:  IN     STD_LOGIC;    
	\4 pdwn\:  IN     STD_LOGIC;    
	\avdd 27\: IN     STD_LOGIC;    
	\avdd 32\: IN     STD_LOGIC;    
	\d0 5\:    OUT    STD_LOGIC;    
	\d1 6\:    OUT    STD_LOGIC;    
	\d10 17\:  OUT    STD_LOGIC;    
	\d11 18\:  OUT    STD_LOGIC;    
	\d12 19\:  OUT    STD_LOGIC;    
	\d13 20\:  OUT    STD_LOGIC;    
	\d2 7\:    OUT    STD_LOGIC;    
	\d3 8\:    OUT    STD_LOGIC;    
	\d4 9\:    OUT    STD_LOGIC;    
	\d5 10\:   OUT    STD_LOGIC;    
	\d6 11\:   OUT    STD_LOGIC;    
	\d7 12\:   OUT    STD_LOGIC;    
	\d8 13\:   OUT    STD_LOGIC;    
	\d9 14\:   OUT    STD_LOGIC;    
	\drvdd 16\: IN     STD_LOGIC;    
	\otr 21\:  OUT    STD_LOGIC;    
	\refb- 25\: IN     STD_LOGIC;    
	\reft- 26\: IN     STD_LOGIC;    
	\vref 24\: IN     STD_LOGIC);
end AD9245;
