// generated by newgenasym  Sat Mar 21 17:56:06 2009


module ltc2620 (\1#20gnd , \10#20sd0 , \11#20clr , \7#20cd/ld , \8#20sck , \9#20sdi , \ref#206 , \vcc#2016 ,
        \vout_a#202 , \vout_b#203 , \vout_c#204 , \vout_d#205 , \vout_e#2012 ,
        \vout_f#2013 , \vout_g#2014 , \vout_h#2015 );
    input \1#20gnd ;
    output \10#20sd0 ;
    input \11#20clr ;
    input \7#20cd/ld ;
    input \8#20sck ;
    input \9#20sdi ;
    input \ref#206 ;
    input \vcc#2016 ;
    output \vout_a#202 ;
    output \vout_b#203 ;
    output \vout_c#204 ;
    output \vout_d#205 ;
    output \vout_e#2012 ;
    output \vout_f#2013 ;
    output \vout_g#2014 ;
    output \vout_h#2015 ;


    initial
        begin
        end

endmodule
