-- generated by newgenasym Sat Mar 21 17:56:06 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LTC2620 is
    port (    
	\1 gnd\:   IN     STD_LOGIC;    
	\10 sd0\:  OUT    STD_LOGIC;    
	\11 clr\:  IN     STD_LOGIC;    
	\7 cd/ld\: IN     STD_LOGIC;    
	\8 sck\:   IN     STD_LOGIC;    
	\9 sdi\:   IN     STD_LOGIC;    
	\ref 6\:   IN     STD_LOGIC;    
	\vcc 16\:  IN     STD_LOGIC;    
	\vout_a 2\: OUT    STD_LOGIC;    
	\vout_b 3\: OUT    STD_LOGIC;    
	\vout_c 4\: OUT    STD_LOGIC;    
	\vout_d 5\: OUT    STD_LOGIC;    
	\vout_e 12\: OUT    STD_LOGIC;    
	\vout_f 13\: OUT    STD_LOGIC;    
	\vout_g 14\: OUT    STD_LOGIC;    
	\vout_h 15\: OUT    STD_LOGIC);
end LTC2620;
