// generated by newgenasym  Wed Mar 29 18:04:30 2006


module microusb (\+3.3v , \+5v , gnd, \reset* , \rx#20data , suspend, \suspend* ,
        \tx#20data );
    input \+3.3v ;
    input \+5v ;
    input gnd;
    input \reset* ;
    input \rx#20data ;
    output suspend;
    output \suspend* ;
    output \tx#20data ;


    initial
        begin
        end

endmodule
