// generated by newgenasym  Fri Dec  4 10:30:25 2009


module \ada4937-2  (\fb1+ , \fb1- , \fb2+ , \fb2- , \in1+ , \in1- , \in2+ , \in2- , \out1+ , \out1- ,
        \out2+ , \out2- , \pd1* , \pd2* , vocm1, vocm2);
    inout \fb1+ ;
    inout \fb1- ;
    inout \fb2+ ;
    inout \fb2- ;
    inout \in1+ ;
    inout \in1- ;
    inout \in2+ ;
    inout \in2- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out2+ ;
    inout \out2- ;
    inout \pd1* ;
    inout \pd2* ;
    inout vocm1;
    inout vocm2;


    initial
        begin
        end

endmodule
