-- generated by newgenasym Fri Dec  4 10:30:25 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ada4937-2\ is
    port (    
	\fb1+\:    INOUT  STD_LOGIC;    
	\fb1-\:    INOUT  STD_LOGIC;    
	\fb2+\:    INOUT  STD_LOGIC;    
	\fb2-\:    INOUT  STD_LOGIC;    
	\in1+\:    INOUT  STD_LOGIC;    
	\in1-\:    INOUT  STD_LOGIC;    
	\in2+\:    INOUT  STD_LOGIC;    
	\in2-\:    INOUT  STD_LOGIC;    
	\out1+\:   INOUT  STD_LOGIC;    
	\out1-\:   INOUT  STD_LOGIC;    
	\out2+\:   INOUT  STD_LOGIC;    
	\out2-\:   INOUT  STD_LOGIC;    
	\pd1*\:    INOUT  STD_LOGIC;    
	\pd2*\:    INOUT  STD_LOGIC;    
	VOCM1:     INOUT  STD_LOGIC;    
	VOCM2:     INOUT  STD_LOGIC);
end \ada4937-2\;
