-- generated by newgenasym Thu Oct 30 18:24:43 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bfu730f is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end bfu730f;
