// generated by newgenasym  Mon Jan 09 16:19:02 2006


module coax_mini (g1, g2, g3, g4, sig);
    input g1;
    input g2;
    input g3;
    input g4;
    input sig;


    initial
        begin
        end

endmodule
