// generated by newgenasym  Mon Jun  7 14:56:42 2010


module at45db642d (cs_n, gnd, reset_n, sck, si, so, vcc, wp_n);
    input cs_n;
    input gnd;
    input reset_n;
    input sck;
    input si;
    output so;
    input vcc;
    input wp_n;


    initial
        begin
        end

endmodule
