-- generated by newgenasym Mon Jun  7 14:56:42 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity at45db642d is
    port (    
	CS_N:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	RESET_N:   IN     STD_LOGIC;    
	SCK:       IN     STD_LOGIC;    
	SI:        IN     STD_LOGIC;    
	SO:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WP_N:      IN     STD_LOGIC);
end at45db642d;
