// generated by newgenasym  Mon May 12 15:58:41 2014


module sn74lvc1g123 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;


    initial
        begin
        end

endmodule
