-- generated by newgenasym Wed Jan 23 20:11:53 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BFS17A is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end BFS17A;
