-- generated by newgenasym Wed Mar 02 01:19:53 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bas70 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end bas70;
