-- generated by newgenasym Thu Feb  3 15:40:54 2000

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CAP_LL is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end CAP_LL;
