-- generated by newgenasym Tue Aug 24 16:29:01 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity coiltronics_drq127 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end coiltronics_drq127;
