// generated by newgenasym  Thu Apr 02 00:42:11 2009


module opa2356 (\+in , \+v , \-in , \-v , out);
    input \+in ;
    input \+v ;
    input \-in ;
    input \-v ;
    output out;


    initial
        begin
        end

endmodule
