-- generated by newgenasym Thu Apr 02 00:42:11 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa2356 is
    port (    
	\+in\:     IN     STD_LOGIC;    
	\+v\:      IN     STD_LOGIC;    
	\-in\:     IN     STD_LOGIC;    
	\-v\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end opa2356;
