// generated by newgenasym  Tue Jun  8 16:37:48 2010


module st2378e (gnd, iovcc1, iovcc2, iovcc3, iovcc4, iovcc5, iovcc6, iovcc7,
        iovcc8, iovl1, iovl2, iovl3, iovl4, iovl5, iovl6, iovl7,
        iovl8, oe, vcc, vl);
    input gnd;
    inout iovcc1;
    inout iovcc2;
    inout iovcc3;
    inout iovcc4;
    inout iovcc5;
    inout iovcc6;
    inout iovcc7;
    inout iovcc8;
    inout iovl1;
    inout iovl2;
    inout iovl3;
    inout iovl4;
    inout iovl5;
    inout iovl6;
    inout iovl7;
    inout iovl8;
    input oe;
    input vcc;
    input vl;


    initial
        begin
        end

endmodule
