// generated by newgenasym  Fri May 30 13:34:24 2014


module tps74201 (bias, en, fb, gnd, in, out, pg, ss);
    inout bias;
    inout en;
    inout fb;
    inout gnd;
    inout in;
    inout out;
    inout pg;
    inout ss;


    initial
        begin
        end

endmodule
