-- generated by newgenasym Mon May 02 15:29:33 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AR510 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end AR510;
