// generated by newgenasym  Thu Jun 15 13:08:16 2006


module qusb2 (clkout, clt, gnd1, gnd2, gnd3, gnd4, gnd5, ifclk, int4, int5b,
        mnt, porta, portb, portc, portd, porte, rdy, reset_b, rxd0,
        rxd1, rxd_0, rxd_1, scl, sda, t0, t1, txd0, txd1, txd_0, txd_1,
        vcc1, vcc2, vcc3, vcc4, vcc5, wakeup_b);
    output clkout;
    output [5:0] clt;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    output ifclk;
    input int4;
    input int5b;
    inout [5:0] mnt;
    inout [7:0] porta;
    inout [7:0] portb;
    inout [7:0] portc;
    inout [7:0] portd;
    inout [7:0] porte;
    input [5:0] rdy;
    output reset_b;
    input rxd0;
    input rxd1;
    input rxd_0;
    input rxd_1;
    input scl;
    input sda;
    input t0;
    input t1;
    output txd0;
    output txd1;
    output txd_0;
    output txd_1;
    inout vcc1;
    inout vcc2;
    inout vcc3;
    inout vcc4;
    inout vcc5;
    input wakeup_b;


    initial
        begin
        end

endmodule
