-- generated by newgenasym Mon Aug 18 13:13:10 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res_0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res_0402;
