// generated by newgenasym  Fri Jun  3 13:32:06 2011


module ad9287 (\clk+ , \clk- , csb, \d+a , \d+b , \d+c , \d+d , \d-a , \d-b , \d-c , \d-d , \dco+ ,
        \dco- , \fco+ , \fco- , pdwn, rbias, refb, reft, sclk, sdio, sense,
        \vin+a , \vin+b , \vin+c , \vin+d , \vin-a , \vin-b , \vin-c , \vin-d , vref);
    input \clk+ ;
    input \clk- ;
    input csb;
    output \d+a ;
    output \d+b ;
    output \d+c ;
    output \d+d ;
    output \d-a ;
    output \d-b ;
    output \d-c ;
    output \d-d ;
    output \dco+ ;
    output \dco- ;
    output \fco+ ;
    output \fco- ;
    input pdwn;
    inout rbias;
    inout refb;
    inout reft;
    input sclk;
    inout sdio;
    inout sense;
    inout \vin+a ;
    inout \vin+b ;
    inout \vin+c ;
    inout \vin+d ;
    inout \vin-a ;
    inout \vin-b ;
    inout \vin-c ;
    inout \vin-d ;
    inout vref;


    initial
        begin
        end

endmodule
