-- generated by newgenasym Mon Sep 08 16:10:56 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity molex_pwr_conn6 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end molex_pwr_conn6;
