// generated by newgenasym  Fri May 06 17:43:18 2011


module d_74hct244 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    output \1 ;
    output \10 ;
    output \11 ;
    output \12 ;
    input \13 ;
    output \14 ;
    input \15 ;
    output \16 ;
    input \17 ;
    output \18 ;
    output \19 ;
    input \2 ;
    input \20 ;
    output \3 ;
    input \4 ;
    output \5 ;
    input \6 ;
    output \7 ;
    input \8 ;
    output \9 ;


    initial
        begin
        end

endmodule
