// generated by newgenasym  Sat Mar 25 05:44:53 2006


module connsip7 (\1 , \2 , \3 , \4 , \5 , \6 , \7 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;


    initial
        begin
        end

endmodule
