-- generated by newgenasym Sat Mar 25 05:44:53 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity connsip7 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC);
end connsip7;
