// generated by newgenasym  Fri Apr 23 10:28:34 2010


module fanout (\in+ , \in- , \out1+ , \out1- , \out2+ , \out2- , \out3+ , \out3- , \out4+ ,
        \out4- , \out5+ , \out5- );
    inout \in+ ;
    inout \in- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out2+ ;
    inout \out2- ;
    inout \out3+ ;
    inout \out3- ;
    inout \out4+ ;
    inout \out4- ;
    inout \out5+ ;
    inout \out5- ;


    initial
        begin
        end

endmodule
