-- generated by newgenasym Fri Apr 23 10:28:34 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fanout is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out1+\:   INOUT  STD_LOGIC;    
	\out1-\:   INOUT  STD_LOGIC;    
	\out2+\:   INOUT  STD_LOGIC;    
	\out2-\:   INOUT  STD_LOGIC;    
	\out3+\:   INOUT  STD_LOGIC;    
	\out3-\:   INOUT  STD_LOGIC;    
	\out4+\:   INOUT  STD_LOGIC;    
	\out4-\:   INOUT  STD_LOGIC;    
	\out5+\:   INOUT  STD_LOGIC;    
	\out5-\:   INOUT  STD_LOGIC);
end fanout;
