// generated by newgenasym  Fri Jun  3 12:50:58 2011


module ad9222 (\clk+ , \clk- , csb, \d+a , \d+b , \d+c , \d+d , \d+e , \d+f , \d+g , \d+h , \d-a ,
        \d-b , \d-c , \d-d , \d-e , \d-f , \d-g , \d-h , \dco+ , \dco- , \fco+ , \fco- , pdwn,
        rbias, refb, reft, sclk, sdio, sense, \vin+a , \vin+b , \vin+c ,
        \vin+d , \vin+e , \vin+f , \vin+g , \vin+h , \vin-a , \vin-b , \vin-c , \vin-d ,
        \vin-e , \vin-f , \vin-g , \vin-h , vref);
    input \clk+ ;
    input \clk- ;
    input csb;
    output \d+a ;
    output \d+b ;
    output \d+c ;
    output \d+d ;
    output \d+e ;
    output \d+f ;
    output \d+g ;
    output \d+h ;
    output \d-a ;
    output \d-b ;
    output \d-c ;
    output \d-d ;
    output \d-e ;
    output \d-f ;
    output \d-g ;
    output \d-h ;
    output \dco+ ;
    output \dco- ;
    output \fco+ ;
    output \fco- ;
    input pdwn;
    inout rbias;
    inout refb;
    inout reft;
    input sclk;
    inout sdio;
    inout sense;
    inout \vin+a ;
    inout \vin+b ;
    inout \vin+c ;
    inout \vin+d ;
    inout \vin+e ;
    inout \vin+f ;
    inout \vin+g ;
    inout \vin+h ;
    inout \vin-a ;
    inout \vin-b ;
    inout \vin-c ;
    inout \vin-d ;
    inout \vin-e ;
    inout \vin-f ;
    inout \vin-g ;
    inout \vin-h ;
    inout vref;


    initial
        begin
        end

endmodule
