// generated by newgenasym  Fri Feb 24 13:24:38 2012


module hdr6 (a1, a2, a3, a4, a5, a6);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;


    initial
        begin
        end

endmodule
