-- generated by newgenasym Tue May 19 17:47:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsmd1206 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end lsmd1206;
