-- generated by newgenasym Thu Jul 26 19:04:47 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1085 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end lt1085;
