// generated by chdl_uprev Tue Nov 11 15:58:56 1997

`timescale 1ns/100ps

module inductor (a, b);
    input [size-1:0] a;
    inout [size-1:0] b;


    IND  inst1[size-1:0] (.A(a),
                               .B(b) );
endmodule