-- generated by newgenasym Mon Jan 09 16:19:41 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity smb_coax is
    port (    
	G1:        IN     STD_LOGIC;    
	G2:        IN     STD_LOGIC;    
	G3:        IN     STD_LOGIC;    
	G4:        IN     STD_LOGIC;    
	SIG:       INOUT  STD_LOGIC);
end smb_coax;
