// generated by newgenasym  Thu Jun 26 17:16:01 2014


module socket8_dip_wide (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;


    initial
        begin
        end

endmodule
