// generated by newgenasym  Fri Mar 24 19:18:31 2006


module conn4 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
