// generated by newgenasym  Mon Dec 06 11:53:49 2010


module \pmtbase-25  (\10 , \14 , \15 , \16 , \17 , \19 , \2 , \20 , \21 , \24 , \25 , \3 , \5 , \7 , \8 , \9 );
    inout \10 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \17 ;
    inout \19 ;
    inout \2 ;
    inout \20 ;
    inout \21 ;
    inout \24 ;
    inout \25 ;
    inout \3 ;
    inout \5 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;


    initial
        begin
        end

endmodule
