-- generated by newgenasym Fri Feb 12 14:46:12 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn10_500mil is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end conn10_500mil;
