-- generated by newgenasym Fri Feb 28 11:45:26 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CSMD1206 is
    port (    
	A:         IN     STD_LOGIC;    
	B:         OUT    STD_LOGIC);
end CSMD1206;
