// generated by newgenasym  Thu Oct 25 13:06:38 2012


module opa2836_single (\1 , \2 , \3 , \4 , \5 , \6 );
    output \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;


    initial
        begin
        end

endmodule
