// generated by newgenasym  Fri Mar 20 13:41:26 2009


module opa356_b (\1 , \2#20-in , \3#20+in , \4#20v- , \5 , \8 , out6, \v+#207 );
    inout \1 ;
    input \2#20-in ;
    input \3#20+in ;
    input \4#20v- ;
    inout \5 ;
    inout \8 ;
    output out6;
    input \v+#207 ;


    initial
        begin
        end

endmodule
