-- generated by newgenasym Fri Mar 20 13:41:26 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa356_b is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2 -in\:   IN     STD_LOGIC;    
	\3 +in\:   IN     STD_LOGIC;    
	\4 v-\:    IN     STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	OUT6:      OUT    STD_LOGIC;    
	\v+ 7\:    IN     STD_LOGIC);
end opa356_b;
