-- generated by newgenasym Wed Oct 17 13:51:47 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity asp_channel1 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	C:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	D:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	E:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	F:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	G:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	H:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	J:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	K:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1));
end asp_channel1;
