// generated by newgenasym  Mon Jul 13 16:46:03 2009


module lvdsrcvr_4x (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    output \12 ;
    output \13 ;
    input \14 ;
    input \15 ;
    input \16 ;
    input \2 ;
    output \3 ;
    output \4 ;
    output \5 ;
    input \6 ;
    input \7 ;
    input \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
