-- generated by newgenasym Mon Jul 13 16:46:03 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LVDSRCVR_4X is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12\:      OUT    STD_LOGIC;    
	\13\:      OUT    STD_LOGIC;    
	\14\:      IN     STD_LOGIC;    
	\15\:      IN     STD_LOGIC;    
	\16\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       OUT    STD_LOGIC;    
	\5\:       OUT    STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end LVDSRCVR_4X;
