-- generated by newgenasym Mon Aug 13 13:13:48 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT3082 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC);
end LT3082;
