-- generated by newgenasym Wed Oct 03 23:05:26 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity samtec_asp_134602_01 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	C:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	D:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	E:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	F:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	G:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	H:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	J:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1);    
	K:         INOUT  STD_LOGIC_VECTOR (40 DOWNTO 1));
end samtec_asp_134602_01;
