-- generated by newgenasym Mon Feb 13 13:27:21 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hv_conn2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end hv_conn2;
