-- generated by newgenasym Fri Feb 24 13:24:38 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hdr6 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC);
end hdr6;
