-- generated by newgenasym Mon Dec 02 17:02:13 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dsm_402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end dsm_402;
