// generated by newgenasym  Mon Sep 15 17:55:07 2014


module lt1185 (\6 , fb, gnd, ref, vin, vout);
    inout \6 ;
    inout fb;
    inout gnd;
    inout ref;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
