-- generated by newgenasym Mon Sep 15 17:55:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1185 is
    port (    
	\6\:       INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end lt1185;
