// generated by newgenasym  Fri Jun  3 17:28:14 2011


module sc1592 (cntl, en, gnd, ilim, in_2, in_3, out_5, out_6, sense);
    inout cntl;
    inout en;
    inout gnd;
    inout ilim;
    inout in_2;
    inout in_3;
    inout out_5;
    inout out_6;
    inout sense;


    initial
        begin
        end

endmodule
