-- generated by newgenasym Mon Jan 09 16:19:02 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity coax_mini is
    port (    
	G1:        IN     STD_LOGIC;    
	G2:        IN     STD_LOGIC;    
	G3:        IN     STD_LOGIC;    
	G4:        IN     STD_LOGIC;    
	SIG:       IN     STD_LOGIC);
end coax_mini;
