// generated by newgenasym  Tue Jun 24 13:41:52 2014


module max8881 (\1 , \2 , \3 , \4 , \5 , \6 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;


    initial
        begin
        end

endmodule
