-- generated by newgenasym Mon Nov 18 16:25:53 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g04 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end sn74lvc1g04;
