-- generated by newgenasym Tue Nov 20 14:19:36 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cdclvc1102 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       OUT    STD_LOGIC);
end cdclvc1102;
