// generated by newgenasym  Mon May 12 13:58:01 2014


module \74hc595_b  (ds, gnd, qa, qb, qc, qd, qe, qf, qg, qh, qhp, shcp, stcp, vcc,
        \|g|* , \|srclr|* );
    input ds;
    input gnd;
    output qa;
    output qb;
    output qc;
    output qd;
    output qe;
    output qf;
    output qg;
    output qh;
    output qhp;
    input shcp;
    input stcp;
    input vcc;
    input \|g|* ;
    input \|srclr|* ;


    initial
        begin
        end

endmodule
