-- generated by newgenasym Wed Mar 17 16:22:19 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd1210 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end csmd1210;
