-- generated by newgenasym Mon Aug  2 15:47:27 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f164\ is
    port (    
	CP:        IN     STD_LOGIC;    
	DSA:       IN     STD_LOGIC;    
	DSB:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0));
end \74f164\;
