-- generated by newgenasym Mon Nov 14 16:57:18 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity agn2004h is
    port (    
	N:         IN     STD_LOGIC;    
	P:         IN     STD_LOGIC;    
	S1A:       INOUT  STD_LOGIC;    
	S1B:       INOUT  STD_LOGIC;    
	S1C:       INOUT  STD_LOGIC;    
	S2A:       INOUT  STD_LOGIC;    
	S2B:       INOUT  STD_LOGIC;    
	S2C:       INOUT  STD_LOGIC);
end agn2004h;
