-- generated by newgenasym Wed May 09 17:52:32 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm50 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end lm50;
