// generated by newgenasym  Mon Oct 08 17:14:04 2012


module ad5328 (p1, p10, p11, p12, p13, p14, p15, p16, p2, p3, p4, p5, p6, p7, p8,
        p9);
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p13;
    inout p14;
    inout p15;
    inout p16;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
