-- generated by newgenasym Wed Mar 12 13:20:16 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DA22F2100L is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end DA22F2100L;
