// generated by newgenasym  Thu Feb  3 15:40:54 2000


module cap_ll (a, b);
    parameter    size = 1;
    inout [size-1:0] b;
    inout [size-1:0] a;


    initial
        begin
        end

endmodule
