// generated by newgenasym  Mon Nov 07 16:29:52 2005


module lmv2011mf (\+ , \- , out, \v+ , \v- );
    inout \+ ;
    inout \- ;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
