-- generated by newgenasym Mon Nov 07 16:29:52 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmv2011mf is
    port (    
	\+\:       INOUT  STD_LOGIC;    
	\-\:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end lmv2011mf;
