// generated by newgenasym  Wed Mar 24 17:27:26 2010


module pmt_base_15 (\1 , \12 , \13 , \14 , \16 , \17 , \18 , \19 , \2 , \20 , \3 , \4 , \5 , \7 , \8 );
    inout \1 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \16 ;
    inout \17 ;
    inout \18 ;
    inout \19 ;
    inout \2 ;
    inout \20 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \7 ;
    inout \8 ;


    initial
        begin
        end

endmodule
