-- generated by newgenasym Wed Mar 24 17:27:26 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pmt_base_15 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\17\:      INOUT  STD_LOGIC;    
	\18\:      INOUT  STD_LOGIC;    
	\19\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\20\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end pmt_base_15;
