// generated by newgenasym  Wed Feb 06 17:23:58 2013


module \smt_spst_mom-sw  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
