// generated by newgenasym  Mon Nov 14 16:57:18 2005


module agn2004h (n, p, s1a, s1b, s1c, s2a, s2b, s2c);
    input n;
    input p;
    inout s1a;
    inout s1b;
    inout s1c;
    inout s2a;
    inout s2b;
    inout s2c;


    initial
        begin
        end

endmodule
