// generated by newgenasym  Fri Jun  3 16:31:18 2011


module ths4520 (cm, cm1, heatsink, nc, \pd* , \vin+ , \vin- , \vout+ , \vout- , \vs+0 ,
        \vs+1 , \vs+2 , \vs+3 , \vs-0 , \vs-1 , \vs-2 , \vs-3 );
    inout cm;
    inout cm1;
    input heatsink;
    inout nc;
    input \pd* ;
    inout \vin+ ;
    inout \vin- ;
    inout \vout+ ;
    inout \vout- ;
    input \vs+0 ;
    input \vs+1 ;
    input \vs+2 ;
    input \vs+3 ;
    input \vs-0 ;
    input \vs-1 ;
    input \vs-2 ;
    input \vs-3 ;


    initial
        begin
        end

endmodule
