// generated by newgenasym  Fri Jun  3 15:51:00 2011


module sy89113u (\clk0+ , \clk0- , \clk1+ , \clk1- , clksel, en, \q0+ , \q0- , \q1+ , \q1- ,
        \q10+ , \q10- , \q11+ , \q11- , \q2+ , \q2- , \q3+ , \q3- , \q4+ , \q4- , \q5+ , \q5- ,
        \q6+ , \q6- , \q7+ , \q7- , \q8+ , \q8- , \q9+ , \q9- , seterm, vbb1, vrefac0,
        vt0);
    input \clk0+ ;
    input \clk0- ;
    input \clk1+ ;
    input \clk1- ;
    input clksel;
    input en;
    output \q0+ ;
    output \q0- ;
    output \q1+ ;
    output \q1- ;
    output \q10+ ;
    output \q10- ;
    output \q11+ ;
    output \q11- ;
    output \q2+ ;
    output \q2- ;
    output \q3+ ;
    output \q3- ;
    output \q4+ ;
    output \q4- ;
    output \q5+ ;
    output \q5- ;
    output \q6+ ;
    output \q6- ;
    output \q7+ ;
    output \q7- ;
    output \q8+ ;
    output \q8- ;
    output \q9+ ;
    output \q9- ;
    inout seterm;
    inout vbb1;
    inout vrefac0;
    inout vt0;


    initial
        begin
        end

endmodule
