-- generated by newgenasym Fri Jun  3 15:51:00 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sy89113u is
    port (    
	\clk0+\:   IN     STD_LOGIC;    
	\clk0-\:   IN     STD_LOGIC;    
	\clk1+\:   IN     STD_LOGIC;    
	\clk1-\:   IN     STD_LOGIC;    
	CLKSEL:    IN     STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	\q0+\:     OUT    STD_LOGIC;    
	\q0-\:     OUT    STD_LOGIC;    
	\q1+\:     OUT    STD_LOGIC;    
	\q1-\:     OUT    STD_LOGIC;    
	\q10+\:    OUT    STD_LOGIC;    
	\q10-\:    OUT    STD_LOGIC;    
	\q11+\:    OUT    STD_LOGIC;    
	\q11-\:    OUT    STD_LOGIC;    
	\q2+\:     OUT    STD_LOGIC;    
	\q2-\:     OUT    STD_LOGIC;    
	\q3+\:     OUT    STD_LOGIC;    
	\q3-\:     OUT    STD_LOGIC;    
	\q4+\:     OUT    STD_LOGIC;    
	\q4-\:     OUT    STD_LOGIC;    
	\q5+\:     OUT    STD_LOGIC;    
	\q5-\:     OUT    STD_LOGIC;    
	\q6+\:     OUT    STD_LOGIC;    
	\q6-\:     OUT    STD_LOGIC;    
	\q7+\:     OUT    STD_LOGIC;    
	\q7-\:     OUT    STD_LOGIC;    
	\q8+\:     OUT    STD_LOGIC;    
	\q8-\:     OUT    STD_LOGIC;    
	\q9+\:     OUT    STD_LOGIC;    
	\q9-\:     OUT    STD_LOGIC;    
	SETERM:    INOUT  STD_LOGIC;    
	VBB1:      INOUT  STD_LOGIC;    
	VREFAC0:   INOUT  STD_LOGIC;    
	VT0:       INOUT  STD_LOGIC);
end sy89113u;
