// generated by newgenasym  Tue Nov 20 14:28:09 2012


module sn65lvds109 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 , \25 ,
        \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \4 , \5 , \6 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    input \12 ;
    input \13 ;
    input \14 ;
    inout \15 ;
    inout \16 ;
    input \17 ;
    input \18 ;
    input \19 ;
    input \2 ;
    output \20 ;
    output \21 ;
    output \22 ;
    output \23 ;
    inout \24 ;
    output \25 ;
    output \26 ;
    output \27 ;
    output \28 ;
    inout \29 ;
    input \3 ;
    output \30 ;
    output \31 ;
    output \32 ;
    output \33 ;
    inout \34 ;
    output \35 ;
    output \36 ;
    output \37 ;
    output \38 ;
    inout \4 ;
    input \5 ;
    input \6 ;
    input \7 ;
    input \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
