-- generated by newgenasym Tue Nov 20 14:28:09 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn65lvds109 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12\:      IN     STD_LOGIC;    
	\13\:      IN     STD_LOGIC;    
	\14\:      IN     STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\17\:      IN     STD_LOGIC;    
	\18\:      IN     STD_LOGIC;    
	\19\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\20\:      OUT    STD_LOGIC;    
	\21\:      OUT    STD_LOGIC;    
	\22\:      OUT    STD_LOGIC;    
	\23\:      OUT    STD_LOGIC;    
	\24\:      INOUT  STD_LOGIC;    
	\25\:      OUT    STD_LOGIC;    
	\26\:      OUT    STD_LOGIC;    
	\27\:      OUT    STD_LOGIC;    
	\28\:      OUT    STD_LOGIC;    
	\29\:      INOUT  STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\30\:      OUT    STD_LOGIC;    
	\31\:      OUT    STD_LOGIC;    
	\32\:      OUT    STD_LOGIC;    
	\33\:      OUT    STD_LOGIC;    
	\34\:      INOUT  STD_LOGIC;    
	\35\:      OUT    STD_LOGIC;    
	\36\:      OUT    STD_LOGIC;    
	\37\:      OUT    STD_LOGIC;    
	\38\:      OUT    STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end sn65lvds109;
