-- generated by newgenasym Fri Apr 25 18:28:52 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tlv70525 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC);
end tlv70525;
