// generated by newgenasym  Sun Mar 16 23:37:24 2008


module mt9v032_b (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \19 , \2 , \20 , \21 , \22 , \23 , \24 , \25 ,
        \26 , \27 , \28 , \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \39 , \4 , \40 , \41 ,
        \42 , \43 , \44 , \45 , \46 , \47 , \48 , \49 , \5 , \50 , \51 , \52 , \53 , \54 , \55 , \56 , \57 , \58 ,
        \59 , \6 , \60 , \61 , \62 , \63 , \64 , \65 , \7 , \8 , \9 );
    output \1 ;
    output \10 ;
    output \11 ;
    input \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    input \17 ;
    input \18 ;
    input \19 ;
    output \2 ;
    input \20 ;
    input \21 ;
    input \22 ;
    input \23 ;
    input \24 ;
    output \25 ;
    output \26 ;
    output \27 ;
    output \28 ;
    inout \29 ;
    output \3 ;
    inout \30 ;
    inout \31 ;
    inout \32 ;
    output \33 ;
    output \34 ;
    output \35 ;
    inout \36 ;
    input \37 ;
    inout \38 ;
    input \39 ;
    output \4 ;
    inout \40 ;
    output \41 ;
    output \42 ;
    input \43 ;
    input \44 ;
    inout \45 ;
    inout \46 ;
    inout \47 ;
    inout \48 ;
    input \49 ;
    inout \5 ;
    input \50 ;
    input \51 ;
    input \52 ;
    input \53 ;
    inout \54 ;
    inout \55 ;
    input \56 ;
    input \57 ;
    input \58 ;
    output \59 ;
    input \6 ;
    output \60 ;
    inout \61 ;
    inout \62 ;
    inout \63 ;
    inout \64 ;
    inout \65 ;
    input \7 ;
    output \8 ;
    output \9 ;


    initial
        begin
        end

endmodule
