// generated by newgenasym  Fri Jun  3 14:06:16 2011


module drs4 (a0, a1, a2, a3, avdd2_5_pin59, avdd2_5_pin65,
        avdd2_5_pin71, avdd2_5_pin76, bias, denable, dspeed, dtap,
        dvdd2_5_pin23, dvdd2_5_pin24, dvdd2_5_pin33,
        dvdd2_5_pin34, dwrite, \in0+ , \in0- , \in1+ , \in1- , \in2+ , \in2- ,
        \in3+ , \in3- , \in4+ , \in4- , \in5+ , \in5- , \in6+ , \in6- , \in7+ , \in7- ,
        \in8+ , \in8- , oofs, \out0+ , \out0- , \out1+ , \out1- , \out2+ , \out2- ,
        \out3+ , \out3- , \out4+ , \out4- , \out5+ , \out5- , \out6+ , \out6- , \out7+ ,
        \out7- , \out8+ , \out8- , plllck, pllout, \refclk+ , \refclk- ,
        \reset* , rofs, rsrload, srclk, srin, srout, wsrin, wsrout);
    input a0;
    input a1;
    input a2;
    input a3;
    input avdd2_5_pin59;
    input avdd2_5_pin65;
    input avdd2_5_pin71;
    input avdd2_5_pin76;
    inout bias;
    input denable;
    inout dspeed;
    output dtap;
    input dvdd2_5_pin23;
    input dvdd2_5_pin24;
    input dvdd2_5_pin33;
    input dvdd2_5_pin34;
    input dwrite;
    inout \in0+ ;
    inout \in0- ;
    inout \in1+ ;
    inout \in1- ;
    inout \in2+ ;
    inout \in2- ;
    inout \in3+ ;
    inout \in3- ;
    inout \in4+ ;
    inout \in4- ;
    inout \in5+ ;
    inout \in5- ;
    inout \in6+ ;
    inout \in6- ;
    inout \in7+ ;
    inout \in7- ;
    inout \in8+ ;
    inout \in8- ;
    inout oofs;
    inout \out0+ ;
    inout \out0- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out2+ ;
    inout \out2- ;
    inout \out3+ ;
    inout \out3- ;
    inout \out4+ ;
    inout \out4- ;
    inout \out5+ ;
    inout \out5- ;
    inout \out6+ ;
    inout \out6- ;
    inout \out7+ ;
    inout \out7- ;
    inout \out8+ ;
    inout \out8- ;
    output plllck;
    inout pllout;
    input \refclk+ ;
    input \refclk- ;
    input \reset* ;
    inout rofs;
    input rsrload;
    input srclk;
    input srin;
    output srout;
    input wsrin;
    output wsrout;


    initial
        begin
        end

endmodule
