// generated by newgenasym  Tue Oct 09 13:05:22 2012


module kc2520c (\1 , \2 , \3 , \4 );
    input \1 ;
    input \2 ;
    output \3 ;
    input \4 ;


    initial
        begin
        end

endmodule
