`timescale 1ns/1ns

module adapter_40pin ();
// generated by  HDL Direct 16.3-p003 (v16-3-85B) 10/27/2009
// on Mon Aug 06 10:20:21 2012
// from mayers_lib/ADAPTER_40PIN/sch_1

  wire  agnd;
  wire  unnamed_1_conn40127mm_i1_1;
  wire  unnamed_1_conn40127mm_i1_10;
  wire  unnamed_1_conn40127mm_i1_11;
  wire  unnamed_1_conn40127mm_i1_12;
  wire  unnamed_1_conn40127mm_i1_13;
  wire  unnamed_1_conn40127mm_i1_14;
  wire  unnamed_1_conn40127mm_i1_15;
  wire  unnamed_1_conn40127mm_i1_16;
  wire  unnamed_1_conn40127mm_i1_17;
  wire  unnamed_1_conn40127mm_i1_18;
  wire  unnamed_1_conn40127mm_i1_19;
  wire  unnamed_1_conn40127mm_i1_2;
  wire  unnamed_1_conn40127mm_i1_20;
  wire  unnamed_1_conn40127mm_i1_21;
  wire  unnamed_1_conn40127mm_i1_22;
  wire  unnamed_1_conn40127mm_i1_23;
  wire  unnamed_1_conn40127mm_i1_24;
  wire  unnamed_1_conn40127mm_i1_25;
  wire  unnamed_1_conn40127mm_i1_26;
  wire  unnamed_1_conn40127mm_i1_27;
  wire  unnamed_1_conn40127mm_i1_28;
  wire  unnamed_1_conn40127mm_i1_29;
  wire  unnamed_1_conn40127mm_i1_3;
  wire  unnamed_1_conn40127mm_i1_30;
  wire  unnamed_1_conn40127mm_i1_31;
  wire  unnamed_1_conn40127mm_i1_32;
  wire  unnamed_1_conn40127mm_i1_33;
  wire  unnamed_1_conn40127mm_i1_34;
  wire  unnamed_1_conn40127mm_i1_35;
  wire  unnamed_1_conn40127mm_i1_36;
  wire  unnamed_1_conn40127mm_i1_37;
  wire  unnamed_1_conn40127mm_i1_38;
  wire  unnamed_1_conn40127mm_i1_39;
  wire  unnamed_1_conn40127mm_i1_4;
  wire  unnamed_1_conn40127mm_i1_40;
  wire  unnamed_1_conn40127mm_i1_5;
  wire  unnamed_1_conn40127mm_i1_6;
  wire  unnamed_1_conn40127mm_i1_7;
  wire  unnamed_1_conn40127mm_i1_8;
  wire  unnamed_1_conn40127mm_i1_9;

// begin instances 

  conn40_127mm page1_i1  (.\1 (unnamed_1_conn40127mm_i1_1),
	.\2 (unnamed_1_conn40127mm_i1_2),
	.\3 (unnamed_1_conn40127mm_i1_3),
	.\4 (unnamed_1_conn40127mm_i1_4),
	.\5 (unnamed_1_conn40127mm_i1_5),
	.\6 (unnamed_1_conn40127mm_i1_6),
	.\7 (unnamed_1_conn40127mm_i1_7),
	.\8 (unnamed_1_conn40127mm_i1_8),
	.\9 (unnamed_1_conn40127mm_i1_9),
	.\10 (unnamed_1_conn40127mm_i1_10),
	.\11 (unnamed_1_conn40127mm_i1_11),
	.\12 (unnamed_1_conn40127mm_i1_12),
	.\13 (unnamed_1_conn40127mm_i1_13),
	.\14 (unnamed_1_conn40127mm_i1_14),
	.\15 (unnamed_1_conn40127mm_i1_15),
	.\16 (unnamed_1_conn40127mm_i1_16),
	.\17 (unnamed_1_conn40127mm_i1_17),
	.\18 (unnamed_1_conn40127mm_i1_18),
	.\19 (unnamed_1_conn40127mm_i1_19),
	.\20 (unnamed_1_conn40127mm_i1_20),
	.\21 (unnamed_1_conn40127mm_i1_21),
	.\22 (unnamed_1_conn40127mm_i1_22),
	.\23 (unnamed_1_conn40127mm_i1_23),
	.\24 (unnamed_1_conn40127mm_i1_24),
	.\25 (unnamed_1_conn40127mm_i1_25),
	.\26 (unnamed_1_conn40127mm_i1_26),
	.\27 (unnamed_1_conn40127mm_i1_27),
	.\28 (unnamed_1_conn40127mm_i1_28),
	.\29 (unnamed_1_conn40127mm_i1_29),
	.\30 (unnamed_1_conn40127mm_i1_30),
	.\31 (unnamed_1_conn40127mm_i1_31),
	.\32 (unnamed_1_conn40127mm_i1_32),
	.\33 (unnamed_1_conn40127mm_i1_33),
	.\34 (unnamed_1_conn40127mm_i1_34),
	.\35 (unnamed_1_conn40127mm_i1_35),
	.\36 (unnamed_1_conn40127mm_i1_36),
	.\37 (unnamed_1_conn40127mm_i1_37),
	.\38 (unnamed_1_conn40127mm_i1_38),
	.\39 (unnamed_1_conn40127mm_i1_39),
	.\40 (unnamed_1_conn40127mm_i1_40),
	.\41 (agnd),
	.\42 (agnd));

  conn40_new page1_i2  (.\1 (unnamed_1_conn40127mm_i1_31),
	.\2 (unnamed_1_conn40127mm_i1_21),
	.\3 (unnamed_1_conn40127mm_i1_32),
	.\4 (unnamed_1_conn40127mm_i1_22),
	.\5 (unnamed_1_conn40127mm_i1_33),
	.\6 (unnamed_1_conn40127mm_i1_23),
	.\7 (unnamed_1_conn40127mm_i1_34),
	.\8 (unnamed_1_conn40127mm_i1_24),
	.\9 (unnamed_1_conn40127mm_i1_35),
	.\10 (unnamed_1_conn40127mm_i1_25),
	.\11 (unnamed_1_conn40127mm_i1_36),
	.\12 (unnamed_1_conn40127mm_i1_26),
	.\13 (unnamed_1_conn40127mm_i1_37),
	.\14 (unnamed_1_conn40127mm_i1_27),
	.\15 (unnamed_1_conn40127mm_i1_38),
	.\16 (unnamed_1_conn40127mm_i1_28),
	.\17 (unnamed_1_conn40127mm_i1_39),
	.\18 (unnamed_1_conn40127mm_i1_29),
	.\19 (unnamed_1_conn40127mm_i1_40),
	.\20 (unnamed_1_conn40127mm_i1_30),
	.\21 (unnamed_1_conn40127mm_i1_10),
	.\22 (unnamed_1_conn40127mm_i1_20),
	.\23 (unnamed_1_conn40127mm_i1_9),
	.\24 (unnamed_1_conn40127mm_i1_19),
	.\25 (unnamed_1_conn40127mm_i1_8),
	.\26 (unnamed_1_conn40127mm_i1_18),
	.\27 (unnamed_1_conn40127mm_i1_7),
	.\28 (unnamed_1_conn40127mm_i1_17),
	.\29 (unnamed_1_conn40127mm_i1_6),
	.\30 (unnamed_1_conn40127mm_i1_16),
	.\31 (unnamed_1_conn40127mm_i1_5),
	.\32 (unnamed_1_conn40127mm_i1_15),
	.\33 (unnamed_1_conn40127mm_i1_4),
	.\34 (unnamed_1_conn40127mm_i1_14),
	.\35 (unnamed_1_conn40127mm_i1_3),
	.\36 (unnamed_1_conn40127mm_i1_13),
	.\37 (unnamed_1_conn40127mm_i1_2),
	.\38 (unnamed_1_conn40127mm_i1_12),
	.\39 (unnamed_1_conn40127mm_i1_1),
	.\40 (unnamed_1_conn40127mm_i1_11),
	.\41 (agnd),
	.\42 (agnd));

endmodule // adapter_40pin(sch_1) 
