-- generated by newgenasym Thu Sep 04 17:08:39 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f04\ is
    port (    
	A:         IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \74f04\;
