// generated by newgenasym  Tue Oct 16 12:25:53 2012


module \8pindipclock  (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    input \1 ;
    inout \2 ;
    inout \3 ;
    input \4 ;
    output \5 ;
    inout \6 ;
    inout \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
