// generated by newgenasym  Tue Aug 19 11:28:11 2014


module lemo_0b (\1 , \3 , \4 , \6 , negative, positive);
    inout \1 ;
    inout \3 ;
    inout \4 ;
    inout \6 ;
    inout negative;
    inout positive;


    initial
        begin
        end

endmodule
