-- generated by newgenasym Tue Aug 19 11:28:11 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lemo_0b is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	NEGATIVE:  INOUT  STD_LOGIC;    
	POSITIVE:  INOUT  STD_LOGIC);
end lemo_0b;
