-- generated by newgenasym Mon Sep 21 13:19:29 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bb_opa350_v2 is
    port (    
	INN:       INOUT  STD_LOGIC;    
	INP:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end bb_opa350_v2;
