// generated by newgenasym  Tue Sep 25 17:43:24 2012


module ltc1407b (\1 , \10 , \11 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    input \1 ;
    input \10 ;
    input \11 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;
    input \7 ;
    output \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
