-- generated by newgenasym Fri Oct 05 17:59:51 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PTH05050 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end PTH05050;
