// generated by newgenasym  Tue Sep 25 17:27:45 2012


module ths4531 (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    output \1 ;
    output \10 ;
    inout \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;
    input \7 ;
    inout \8 ;
    output \9 ;


    initial
        begin
        end

endmodule
