-- generated by newgenasym Wed Sep 20 14:42:07 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \2n4124\ is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end \2n4124\;
