-- generated by newgenasym Wed Apr 27 17:29:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \_rsmd0402b\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \_rsmd0402b\;
