-- generated by newgenasym Wed Mar 29 18:04:30 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity microusb is
    port (    
	\+3.3v\:   IN     STD_LOGIC;    
	\+5v\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	\rx data\: IN     STD_LOGIC;    
	SUSPEND:   OUT    STD_LOGIC;    
	\suspend*\: OUT    STD_LOGIC;    
	\tx data\: OUT    STD_LOGIC);
end microusb;
