-- generated by newgenasym Thu Aug 26 14:00:27 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_1206 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cap_1206;
