-- generated by newgenasym Thu Nov 14 12:16:24 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmh6618 is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC);
end lmh6618;
