-- generated by newgenasym Thu Jun 17 17:30:09 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max6035 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end max6035;
