-- generated by newgenasym Tue Jun 16 14:43:53 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity JUMPER is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end JUMPER;
