// generated by newgenasym  Tue Oct 09 19:52:01 2012


module sn65lvdt2 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
