-- generated by newgenasym Tue Oct 09 19:52:01 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SN65LVDT2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end SN65LVDT2;
