// generated by newgenasym  Thu Dec 22 17:41:07 2016


module lmc555 (ctrl, disch, gnd, out, res, thresh, trig, \v+ );
    inout ctrl;
    inout disch;
    inout gnd;
    inout out;
    inout res;
    inout thresh;
    inout trig;
    inout \v+ ;


    initial
        begin
        end

endmodule
