-- generated by newgenasym Thu Dec 22 17:41:07 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmc555 is
    port (    
	CTRL:      INOUT  STD_LOGIC;    
	DISCH:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	RES:       INOUT  STD_LOGIC;    
	THRESH:    INOUT  STD_LOGIC;    
	TRIG:      INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC);
end lmc555;
