// generated by newgenasym  Fri Feb 24 00:33:49 2006


module mc68hc908gr8 (cgmfxc, \irq* , osc1, osc2, \pta0/kbd0 , \pta1/kbd1 , \pta2/kbd2 ,
        \pta3/kbd3 , \ptb0/ad0 , \ptb1/ad1 , \ptb2/ad2 , \ptb3/ad3 ,
        \ptb4/ad4 , \ptb5/ad5 , ptc0, ptc1, \ptd0/ss , \ptd1/miso ,
        \ptd2/mosi , \ptd3/spsck , \ptd4/t1ch0 , \ptd5/t1ch1 , \ptd6/t2ch0 ,
        \pte0/txd , \pte1/rxd , \rst* , vdd, vdda, \vddad/vrefh , vss, vssa,
        \vssad/vrefl );
    input cgmfxc;
    input \irq* ;
    input osc1;
    input osc2;
    inout \pta0/kbd0 ;
    inout \pta1/kbd1 ;
    inout \pta2/kbd2 ;
    inout \pta3/kbd3 ;
    inout \ptb0/ad0 ;
    inout \ptb1/ad1 ;
    inout \ptb2/ad2 ;
    inout \ptb3/ad3 ;
    inout \ptb4/ad4 ;
    inout \ptb5/ad5 ;
    inout ptc0;
    inout ptc1;
    inout \ptd0/ss ;
    inout \ptd1/miso ;
    inout \ptd2/mosi ;
    inout \ptd3/spsck ;
    inout \ptd4/t1ch0 ;
    inout \ptd5/t1ch1 ;
    inout \ptd6/t2ch0 ;
    inout \pte0/txd ;
    inout \pte1/rxd ;
    input \rst* ;
    input vdd;
    input vdda;
    input \vddad/vrefh ;
    input vss;
    input vssa;
    input \vssad/vrefl ;


    initial
        begin
        end

endmodule
