-- generated by newgenasym Wed Aug 12 11:28:31 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity GEN891009_37 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P10:       INOUT  STD_LOGIC;    
	P11:       INOUT  STD_LOGIC;    
	P12:       INOUT  STD_LOGIC;    
	P13:       INOUT  STD_LOGIC;    
	P14:       INOUT  STD_LOGIC;    
	P15:       INOUT  STD_LOGIC;    
	P16:       INOUT  STD_LOGIC;    
	P17:       INOUT  STD_LOGIC;    
	P18:       INOUT  STD_LOGIC;    
	P19:       INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P20:       INOUT  STD_LOGIC;    
	P21:       INOUT  STD_LOGIC;    
	P22:       INOUT  STD_LOGIC;    
	P23:       INOUT  STD_LOGIC;    
	P24:       INOUT  STD_LOGIC;    
	P25:       INOUT  STD_LOGIC;    
	P26:       INOUT  STD_LOGIC;    
	P27:       INOUT  STD_LOGIC;    
	P28:       INOUT  STD_LOGIC;    
	P29:       INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P30:       INOUT  STD_LOGIC;    
	P31:       INOUT  STD_LOGIC;    
	P32:       INOUT  STD_LOGIC;    
	P33:       INOUT  STD_LOGIC;    
	P34:       INOUT  STD_LOGIC;    
	P35:       INOUT  STD_LOGIC;    
	P36:       INOUT  STD_LOGIC;    
	P37:       INOUT  STD_LOGIC;    
	P38:       INOUT  STD_LOGIC;    
	P39:       INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC;    
	P5:        INOUT  STD_LOGIC;    
	P6:        INOUT  STD_LOGIC;    
	P7:        INOUT  STD_LOGIC;    
	P8:        INOUT  STD_LOGIC;    
	P9:        INOUT  STD_LOGIC);
end GEN891009_37;
