// generated by newgenasym  Wed Nov 25 13:54:17 2015


module testpart (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    input \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
