// generated by newgenasym  Fri Aug 17 19:48:13 2012


module ad7982 (p1, p10, p2, p3, p4, p5, p6, p7, p8, p9);
    inout p1;
    inout p10;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
