-- generated by newgenasym Fri Jun  3 16:31:18 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths4520 is
    port (    
	CM:        INOUT  STD_LOGIC;    
	CM1:       INOUT  STD_LOGIC;    
	HEATSINK:  IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\pd*\:     IN     STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	\vout+\:   INOUT  STD_LOGIC;    
	\vout-\:   INOUT  STD_LOGIC;    
	\vs+0\:    IN     STD_LOGIC;    
	\vs+1\:    IN     STD_LOGIC;    
	\vs+2\:    IN     STD_LOGIC;    
	\vs+3\:    IN     STD_LOGIC;    
	\vs-0\:    IN     STD_LOGIC;    
	\vs-1\:    IN     STD_LOGIC;    
	\vs-2\:    IN     STD_LOGIC;    
	\vs-3\:    IN     STD_LOGIC);
end ths4520;
