-- generated by newgenasym Tue Jun 05 16:30:07 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1185 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end lt1185;
