-- generated by newgenasym Tue Feb 10 13:41:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mec8_card30b is
    port (    
	\10\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\18\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\20\:      INOUT  STD_LOGIC;    
	\22\:      INOUT  STD_LOGIC;    
	\24\:      INOUT  STD_LOGIC;    
	\26\:      INOUT  STD_LOGIC;    
	\28\:      INOUT  STD_LOGIC;    
	\30\:      INOUT  STD_LOGIC;    
	\32\:      INOUT  STD_LOGIC;    
	\34\:      INOUT  STD_LOGIC;    
	\36\:      INOUT  STD_LOGIC;    
	\38\:      INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\40\:      INOUT  STD_LOGIC;    
	\42\:      INOUT  STD_LOGIC;    
	\44\:      INOUT  STD_LOGIC;    
	\46\:      INOUT  STD_LOGIC;    
	\48\:      INOUT  STD_LOGIC;    
	\50\:      INOUT  STD_LOGIC;    
	\52\:      INOUT  STD_LOGIC;    
	\54\:      INOUT  STD_LOGIC;    
	\56\:      INOUT  STD_LOGIC;    
	\58\:      INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\60\:      INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end mec8_card30b;
