// generated by newgenasym  Wed Dec 28 10:49:23 2016


module adn4661 (din, \dout+ , \dout- , gnd, nc1, nc2, nc3, vcc);
    inout din;
    inout \dout+ ;
    inout \dout- ;
    inout gnd;
    inout nc1;
    inout nc2;
    inout nc3;
    inout vcc;


    initial
        begin
        end

endmodule
