-- generated by newgenasym Wed Dec 28 10:49:23 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adn4661 is
    port (    
	DIN:       INOUT  STD_LOGIC;    
	\dout+\:   INOUT  STD_LOGIC;    
	\dout-\:   INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end adn4661;
