// generated by newgenasym  Sat Mar 21 16:45:02 2009


module lt1763_33 (\10#20in , \11#20in , \13#20gnd/hsk , \7#20gnd , \8#20shdn , \byp#206 , \nc#201 , \nc#204 ,
        \nc#209 , nc12, \out#202 , \out#203 , \sense/adj#205 );
    input \10#20in ;
    input \11#20in ;
    input \13#20gnd/hsk ;
    input \7#20gnd ;
    input \8#20shdn ;
    output \byp#206 ;
    inout \nc#201 ;
    inout \nc#204 ;
    inout \nc#209 ;
    inout nc12;
    output \out#202 ;
    output \out#203 ;
    inout \sense/adj#205 ;


    initial
        begin
        end

endmodule
