-- generated by newgenasym Thu Oct 19 08:41:16 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sst4416_njfet is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end sst4416_njfet;
