// generated by newgenasym  Wed Sep 19 15:00:24 2012


module so_dimm (\1 , \10 , \100 , \101 , \102 , \103 , \104 , \105 , \106 , \107 , \108 , \109 , \11 , \110 ,
        \111 , \112 , \113 , \114 , \115 , \116 , \117 , \118 , \119 , \12 , \120 , \121 , \122 ,
        \123 , \124 , \125 , \126 , \127 , \128 , \129 , \13 , \130 , \131 , \132 , \133 , \134 ,
        \135 , \136 , \137 , \138 , \139 , \14 , \140 , \141 , \142 , \143 , \144 , \145 , \146 ,
        \147 , \148 , \149 , \15 , \150 , \151 , \152 , \153 , \154 , \155 , \156 , \157 , \158 ,
        \159 , \16 , \160 , \161 , \162 , \163 , \164 , \165 , \166 , \167 , \168 , \169 , \17 , \170 ,
        \171 , \172 , \173 , \174 , \175 , \176 , \177 , \178 , \179 , \18 , \180 , \181 , \182 ,
        \183 , \184 , \185 , \186 , \187 , \188 , \189 , \19 , \190 , \191 , \192 , \193 , \194 ,
        \195 , \196 , \197 , \198 , \199 , \2 , \20 , \200 , \21 , \22 , \23 , \24 , \25 , \26 , \27 , \28 ,
        \29 , \3 , \30 , \31 , \32 , \33 , \34 , \35 , \36 , \37 , \38 , \39 , \4 , \40 , \41 , \42 , \43 , \44 ,
        \45 , \46 , \47 , \48 , \49 , \5 , \50 , \51 , \52 , \53 , \54 , \55 , \56 , \57 , \58 , \59 , \6 , \60 ,
        \61 , \62 , \63 , \64 , \65 , \66 , \67 , \68 , \69 , \7 , \70 , \71 , \72 , \73 , \74 , \75 , \76 , \77 ,
        \78 , \79 , \8 , \80 , \81 , \82 , \83 , \84 , \85 , \86 , \87 , \88 , \89 , \9 , \90 , \91 , \92 , \93 ,
        \94 , \95 , \96 , \97 , \98 , \99 );
    inout \1 ;
    inout \10 ;
    inout \100 ;
    inout \101 ;
    inout \102 ;
    inout \103 ;
    inout \104 ;
    inout \105 ;
    inout \106 ;
    inout \107 ;
    inout \108 ;
    inout \109 ;
    inout \11 ;
    inout \110 ;
    inout \111 ;
    inout \112 ;
    inout \113 ;
    inout \114 ;
    inout \115 ;
    inout \116 ;
    inout \117 ;
    inout \118 ;
    inout \119 ;
    inout \12 ;
    inout \120 ;
    inout \121 ;
    inout \122 ;
    inout \123 ;
    inout \124 ;
    inout \125 ;
    inout \126 ;
    inout \127 ;
    inout \128 ;
    inout \129 ;
    inout \13 ;
    inout \130 ;
    inout \131 ;
    inout \132 ;
    inout \133 ;
    inout \134 ;
    inout \135 ;
    inout \136 ;
    inout \137 ;
    inout \138 ;
    inout \139 ;
    inout \14 ;
    inout \140 ;
    inout \141 ;
    inout \142 ;
    inout \143 ;
    inout \144 ;
    inout \145 ;
    inout \146 ;
    inout \147 ;
    inout \148 ;
    inout \149 ;
    inout \15 ;
    inout \150 ;
    inout \151 ;
    inout \152 ;
    inout \153 ;
    inout \154 ;
    inout \155 ;
    inout \156 ;
    inout \157 ;
    inout \158 ;
    inout \159 ;
    inout \16 ;
    inout \160 ;
    inout \161 ;
    inout \162 ;
    inout \163 ;
    inout \164 ;
    inout \165 ;
    inout \166 ;
    inout \167 ;
    inout \168 ;
    inout \169 ;
    inout \17 ;
    inout \170 ;
    inout \171 ;
    inout \172 ;
    inout \173 ;
    inout \174 ;
    inout \175 ;
    inout \176 ;
    inout \177 ;
    inout \178 ;
    inout \179 ;
    inout \18 ;
    inout \180 ;
    inout \181 ;
    inout \182 ;
    inout \183 ;
    inout \184 ;
    inout \185 ;
    inout \186 ;
    inout \187 ;
    inout \188 ;
    inout \189 ;
    inout \19 ;
    inout \190 ;
    inout \191 ;
    inout \192 ;
    inout \193 ;
    inout \194 ;
    inout \195 ;
    inout \196 ;
    inout \197 ;
    inout \198 ;
    inout \199 ;
    inout \2 ;
    inout \20 ;
    inout \200 ;
    inout \21 ;
    inout \22 ;
    inout \23 ;
    inout \24 ;
    inout \25 ;
    inout \26 ;
    inout \27 ;
    inout \28 ;
    inout \29 ;
    inout \3 ;
    inout \30 ;
    inout \31 ;
    inout \32 ;
    inout \33 ;
    inout \34 ;
    inout \35 ;
    inout \36 ;
    inout \37 ;
    inout \38 ;
    inout \39 ;
    inout \4 ;
    inout \40 ;
    inout \41 ;
    inout \42 ;
    inout \43 ;
    inout \44 ;
    inout \45 ;
    inout \46 ;
    inout \47 ;
    inout \48 ;
    inout \49 ;
    inout \5 ;
    inout \50 ;
    inout \51 ;
    inout \52 ;
    inout \53 ;
    inout \54 ;
    inout \55 ;
    inout \56 ;
    inout \57 ;
    inout \58 ;
    inout \59 ;
    inout \6 ;
    inout \60 ;
    inout \61 ;
    inout \62 ;
    inout \63 ;
    inout \64 ;
    inout \65 ;
    inout \66 ;
    inout \67 ;
    inout \68 ;
    inout \69 ;
    inout \7 ;
    inout \70 ;
    inout \71 ;
    inout \72 ;
    inout \73 ;
    inout \74 ;
    inout \75 ;
    inout \76 ;
    inout \77 ;
    inout \78 ;
    inout \79 ;
    inout \8 ;
    inout \80 ;
    inout \81 ;
    inout \82 ;
    inout \83 ;
    inout \84 ;
    inout \85 ;
    inout \86 ;
    inout \87 ;
    inout \88 ;
    inout \89 ;
    inout \9 ;
    inout \90 ;
    inout \91 ;
    inout \92 ;
    inout \93 ;
    inout \94 ;
    inout \95 ;
    inout \96 ;
    inout \97 ;
    inout \98 ;
    inout \99 ;


    initial
        begin
        end

endmodule
