-- generated by newgenasym Sun Nov 17 01:03:26 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity acx1991 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end acx1991;
