// generated by newgenasym  Mon Mar 16 15:39:12 2009


module mec8_conn30b (\10 , \12 , \14 , \16 , \18 , \2 , \20 , \22 , \24 , \26 , \28 , \30 , \32 , \34 , \36 , \38 , \4 , \40 ,
        \42 , \44 , \46 , \48 , \50 , \52 , \54 , \56 , \58 , \6 , \60 , \8 );
    inout \10 ;
    inout \12 ;
    inout \14 ;
    inout \16 ;
    inout \18 ;
    inout \2 ;
    inout \20 ;
    inout \22 ;
    inout \24 ;
    inout \26 ;
    inout \28 ;
    inout \30 ;
    inout \32 ;
    inout \34 ;
    inout \36 ;
    inout \38 ;
    inout \4 ;
    inout \40 ;
    inout \42 ;
    inout \44 ;
    inout \46 ;
    inout \48 ;
    inout \50 ;
    inout \52 ;
    inout \54 ;
    inout \56 ;
    inout \58 ;
    inout \6 ;
    inout \60 ;
    inout \8 ;


    initial
        begin
        end

endmodule
