-- generated by newgenasym Fri May 14 12:05:01 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led160x80mm is
    port (    
	\1plus\:   INOUT  STD_LOGIC;    
	\2minus\:  INOUT  STD_LOGIC);
end led160x80mm;
