// generated by newgenasym  Sat Nov 16 21:48:07 2013


module ad9628_sp (avdd1, avdd2, avdd3, avdd4, avdd5, avdd6, avdd7, avdd8,
        clk_n, clk_p, csb, d0a, d0b, d10a, d10b, d11a, d11b, d1a, d1b,
        d2a, d2b, d3a, d3b, d4a, d4b, d5a, d5b, d6a, d6b, d7a, d7b, d8a,
        d8b, d9a, d9b, dcoa, dcob, drvdd1, drvdd2, drvdd3, drvdd4, gnd,
        nc1, nc2, nc3, nc4, nc5, nc6, nc7, nc8, nc9, ora, orb, pdwn,
        rbias, \sclk/dfs , \sdio/dcs , sense, sync, vcm, \vin+a , \vin+b ,
        \vin-a , \vin-b , vref);
    inout avdd1;
    inout avdd2;
    inout avdd3;
    inout avdd4;
    inout avdd5;
    inout avdd6;
    inout avdd7;
    inout avdd8;
    inout clk_n;
    inout clk_p;
    inout csb;
    inout d0a;
    inout d0b;
    inout d10a;
    inout d10b;
    inout d11a;
    inout d11b;
    inout d1a;
    inout d1b;
    inout d2a;
    inout d2b;
    inout d3a;
    inout d3b;
    inout d4a;
    inout d4b;
    inout d5a;
    inout d5b;
    inout d6a;
    inout d6b;
    inout d7a;
    inout d7b;
    inout d8a;
    inout d8b;
    inout d9a;
    inout d9b;
    inout dcoa;
    inout dcob;
    inout drvdd1;
    inout drvdd2;
    inout drvdd3;
    inout drvdd4;
    inout gnd;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    inout ora;
    inout orb;
    inout pdwn;
    inout rbias;
    inout \sclk/dfs ;
    inout \sdio/dcs ;
    inout sense;
    inout sync;
    inout vcm;
    inout \vin+a ;
    inout \vin+b ;
    inout \vin-a ;
    inout \vin-b ;
    inout vref;


    initial
        begin
        end

endmodule
