// generated by newgenasym  Thu May 31 18:01:19 2012


module opa2835_m (pd, \v_in+ , \v_in- , v_out);
    input pd;
    input \v_in+ ;
    input \v_in- ;
    output v_out;


    initial
        begin
        end

endmodule
