-- generated by newgenasym Mon Jun 08 16:14:43 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TRIMPOT_635SQ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end TRIMPOT_635SQ;
