// generated by newgenasym  Wed Nov 17 16:47:41 2004


module powerreglt1185 (fb, gnd, mount, ref, vin, vout);
    input fb;
    input gnd;
    input mount;
    input ref;
    input vin;
    input vout;


    initial
        begin
        end

endmodule
