-- generated by newgenasym Tue Sep 11 12:49:31 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mounthole250_138 is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end mounthole250_138;
