-- generated by newgenasym Tue Aug 24 14:00:08 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fuse_axial_473 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end fuse_axial_473;
