-- generated by newgenasym Fri Feb 17 15:01:32 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pot_sm is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end pot_sm;
