// generated by newgenasym  Fri Dec  4 11:24:05 2009


module mitch_fanout_3 (in, out1, out2, out3);
    inout in;
    inout out1;
    inout out2;
    inout out3;


    initial
        begin
        end

endmodule
