-- generated by newgenasym Fri Dec  4 11:24:05 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mitch_fanout_3 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC);
end mitch_fanout_3;
