// generated by newgenasym  Tue Mar 24 10:36:48 2009


module opa356 (\2v- , \3+in , \4-in , out1, \v+5 );
    input \2v- ;
    input \3+in ;
    input \4-in ;
    output out1;
    input \v+5 ;


    initial
        begin
        end

endmodule
