-- generated by newgenasym Tue Mar 24 10:36:48 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPA356 is
    port (    
	\2v-\:     IN     STD_LOGIC;    
	\3+in\:    IN     STD_LOGIC;    
	\4-in\:    IN     STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	\v+5\:     IN     STD_LOGIC);
end OPA356;
