-- generated by newgenasym Wed Jun 06 11:25:25 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT_1185 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end LT_1185;
