// generated by newgenasym  Tue Oct 02 17:45:06 2012


module adm3202aruz (\c1+ , \c1- , \c2+ , \c2- , gnd, r1in, r1out, r2in, r2out, t1in, t1out,
        t2in, t2out, \v+ , \v- , vcc);
    inout \c1+ ;
    inout \c1- ;
    inout \c2+ ;
    inout \c2- ;
    inout gnd;
    inout r1in;
    inout r1out;
    inout r2in;
    inout r2out;
    inout t1in;
    inout t1out;
    inout t2in;
    inout t2out;
    inout \v+ ;
    inout \v- ;
    inout vcc;


    initial
        begin
        end

endmodule
