-- generated by newgenasym Tue Oct 02 17:45:06 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADM3202ARUZ is
    port (    
	\c1+\:     INOUT  STD_LOGIC;    
	\c1-\:     INOUT  STD_LOGIC;    
	\c2+\:     INOUT  STD_LOGIC;    
	\c2-\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	R1IN:      INOUT  STD_LOGIC;    
	R1OUT:     INOUT  STD_LOGIC;    
	R2IN:      INOUT  STD_LOGIC;    
	R2OUT:     INOUT  STD_LOGIC;    
	T1IN:      INOUT  STD_LOGIC;    
	T1OUT:     INOUT  STD_LOGIC;    
	T2IN:      INOUT  STD_LOGIC;    
	T2OUT:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ADM3202ARUZ;
