// generated by newgenasym  Thu Mar 19 19:52:11 2009


module opa356b (\2-in , \3+in , \4v- , nc1, out6, \v+7 );
    input \2-in ;
    input \3+in ;
    input \4v- ;
    inout nc1;
    output out6;
    input \v+7 ;


    initial
        begin
        end

endmodule
