// generated by newgenasym  Wed Sep 22 17:04:03 2010


module lt3957 (en, fbx, gnd_12, gnd_13, gnd_14, gnd_15, gnd_16, gnd_17,
        intvcc, rt, sense1, sense2, sgnd_23, sgnd_24, sgnd_37,
        sgnd_4, ss, sw_20, sw_21, sw_38, sw_8, sw_9, sync, vc, vin);
    inout en;
    inout fbx;
    inout gnd_12;
    inout gnd_13;
    inout gnd_14;
    inout gnd_15;
    inout gnd_16;
    inout gnd_17;
    inout intvcc;
    inout rt;
    inout sense1;
    inout sense2;
    inout sgnd_23;
    inout sgnd_24;
    inout sgnd_37;
    inout sgnd_4;
    inout ss;
    inout sw_20;
    inout sw_21;
    inout sw_38;
    inout sw_8;
    inout sw_9;
    inout sync;
    inout vc;
    inout vin;


    initial
        begin
        end

endmodule
