-- generated by newgenasym Wed Sep 22 17:04:03 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt3957 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FBX:       INOUT  STD_LOGIC;    
	GND_12:    INOUT  STD_LOGIC;    
	GND_13:    INOUT  STD_LOGIC;    
	GND_14:    INOUT  STD_LOGIC;    
	GND_15:    INOUT  STD_LOGIC;    
	GND_16:    INOUT  STD_LOGIC;    
	GND_17:    INOUT  STD_LOGIC;    
	INTVCC:    INOUT  STD_LOGIC;    
	RT:        INOUT  STD_LOGIC;    
	SENSE1:    INOUT  STD_LOGIC;    
	SENSE2:    INOUT  STD_LOGIC;    
	SGND_23:   INOUT  STD_LOGIC;    
	SGND_24:   INOUT  STD_LOGIC;    
	SGND_37:   INOUT  STD_LOGIC;    
	SGND_4:    INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	SW_20:     INOUT  STD_LOGIC;    
	SW_21:     INOUT  STD_LOGIC;    
	SW_38:     INOUT  STD_LOGIC;    
	SW_8:      INOUT  STD_LOGIC;    
	SW_9:      INOUT  STD_LOGIC;    
	SYNC:      INOUT  STD_LOGIC;    
	VC:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end lt3957;
