// generated by newgenasym  Mon Jun  6 12:09:52 2011


module lan8710 (col, crs, gnd, led1, led2, mdc, mdio, nint, nrst, rbias, rxclk,
        rxd0, rxd1, rxd2, rxd3, rxdv, rxer, rxn, rxp, txclk, txd0, txd1,
        txd2, txd3, txen, txn, txp, vdd1a, vdd2a, vddcr, vddio, xtal1,
        xtal2);
    output col;
    output crs;
    input gnd;
    output led1;
    output led2;
    input mdc;
    inout mdio;
    output nint;
    input nrst;
    inout rbias;
    output rxclk;
    output rxd0;
    output rxd1;
    output rxd2;
    output rxd3;
    output rxdv;
    output rxer;
    inout rxn;
    inout rxp;
    output txclk;
    input txd0;
    input txd1;
    input txd2;
    input txd3;
    input txen;
    inout txn;
    inout txp;
    input vdd1a;
    input vdd2a;
    input vddcr;
    input vddio;
    input xtal1;
    output xtal2;


    initial
        begin
        end

endmodule
