-- generated by newgenasym Mon Jun  6 12:09:53 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lan8710 is
    port (    
	COL:       OUT    STD_LOGIC;    
	CRS:       OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	LED1:      OUT    STD_LOGIC;    
	LED2:      OUT    STD_LOGIC;    
	MDC:       IN     STD_LOGIC;    
	MDIO:      INOUT  STD_LOGIC;    
	NINT:      OUT    STD_LOGIC;    
	NRST:      IN     STD_LOGIC;    
	RBIAS:     INOUT  STD_LOGIC;    
	RXCLK:     OUT    STD_LOGIC;    
	RXD0:      OUT    STD_LOGIC;    
	RXD1:      OUT    STD_LOGIC;    
	RXD2:      OUT    STD_LOGIC;    
	RXD3:      OUT    STD_LOGIC;    
	RXDV:      OUT    STD_LOGIC;    
	RXER:      OUT    STD_LOGIC;    
	RXN:       INOUT  STD_LOGIC;    
	RXP:       INOUT  STD_LOGIC;    
	TXCLK:     OUT    STD_LOGIC;    
	TXD0:      IN     STD_LOGIC;    
	TXD1:      IN     STD_LOGIC;    
	TXD2:      IN     STD_LOGIC;    
	TXD3:      IN     STD_LOGIC;    
	TXEN:      IN     STD_LOGIC;    
	TXN:       INOUT  STD_LOGIC;    
	TXP:       INOUT  STD_LOGIC;    
	VDD1A:     IN     STD_LOGIC;    
	VDD2A:     IN     STD_LOGIC;    
	VDDCR:     IN     STD_LOGIC;    
	VDDIO:     IN     STD_LOGIC;    
	XTAL1:     IN     STD_LOGIC;    
	XTAL2:     OUT    STD_LOGIC);
end lan8710;
