-- generated by newgenasym Thu Dec 08 12:35:41 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SMSWITCHDPDT is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC;    
	F:         INOUT  STD_LOGIC);
end SMSWITCHDPDT;
