// generated by newgenasym  Wed Mar 06 16:47:36 2013


module lmh6611 (\1 , \2 , \3 , \4 , \5 , \6 );
    output \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;


    initial
        begin
        end

endmodule
