// generated by newgenasym  Mon Oct 15 12:31:44 2012


module ada4841_2 (p1, p2, p3, p4, p5, p6, p7, p8, p9);
    inout p1;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
