// generated by newgenasym  Tue Aug 24 16:29:01 2010


module coiltronics_drq127 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
