// generated by newgenasym  Wed Mar 25 22:32:17 2009


module ad8351 (\1#20pwup , \10#20vocm , \2#20rgp1 , \3#20inhi , \4#20inlo , \5#20rgp2 , \6#20comm ,
        \7#20oplo , \8#20ophi , \9#20vpos );
    input \1#20pwup ;
    input \10#20vocm ;
    input \2#20rgp1 ;
    input \3#20inhi ;
    input \4#20inlo ;
    input \5#20rgp2 ;
    input \6#20comm ;
    output \7#20oplo ;
    output \8#20ophi ;
    input \9#20vpos ;


    initial
        begin
        end

endmodule
