-- generated by newgenasym Wed Mar 25 22:32:17 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD8351 is
    port (    
	\1 pwup\:  IN     STD_LOGIC;    
	\10 vocm\: IN     STD_LOGIC;    
	\2 rgp1\:  IN     STD_LOGIC;    
	\3 inhi\:  IN     STD_LOGIC;    
	\4 inlo\:  IN     STD_LOGIC;    
	\5 rgp2\:  IN     STD_LOGIC;    
	\6 comm\:  IN     STD_LOGIC;    
	\7 oplo\:  OUT    STD_LOGIC;    
	\8 ophi\:  OUT    STD_LOGIC;    
	\9 vpos\:  IN     STD_LOGIC);
end AD8351;
