// generated by newgenasym  Thu Jan 12 16:24:01 2006


module mc100el51 (clk, \clk* , d, q, \q* , r, vcc, vee);
    inout clk;
    inout \clk* ;
    inout d;
    inout q;
    inout \q* ;
    inout r;
    inout vcc;
    inout vee;


    initial
        begin
        end

endmodule
