-- generated by newgenasym Thu Jul 10 14:33:23 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BFU690F is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end BFU690F;
