-- generated by newgenasym Fri Oct 24 17:27:24 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps73x01 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end tps73x01;
