-- generated by newgenasym Thu Feb 04 12:55:45 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_0603 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cap_0603;
