// generated by newgenasym  Fri Jan 06 10:23:19 2017


module hfa3128b96 (b1, b2, b3, b4, b5, c1, c2, c3, c4, c5, e1, e2, e3, e4, e5, nc1);
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout c1;
    inout c2;
    inout c3;
    inout c4;
    inout c5;
    inout e1;
    inout e2;
    inout e3;
    inout e4;
    inout e5;
    inout nc1;


    initial
        begin
        end

endmodule
