-- generated by newgenasym Fri Jan 06 10:23:19 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hfa3128b96 is
    port (    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	C3:        INOUT  STD_LOGIC;    
	C4:        INOUT  STD_LOGIC;    
	C5:        INOUT  STD_LOGIC;    
	E1:        INOUT  STD_LOGIC;    
	E2:        INOUT  STD_LOGIC;    
	E3:        INOUT  STD_LOGIC;    
	E4:        INOUT  STD_LOGIC;    
	E5:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC);
end hfa3128b96;
