-- generated by newgenasym Thu Jan 03 16:35:46 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RSMD1005 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end RSMD1005;
