-- generated by newgenasym Fri Mar 31 11:10:34 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds26ls32 is
    port (    
	\1a\:      IN     STD_LOGIC;    
	\1b\:      IN     STD_LOGIC;    
	\1y\:      OUT    STD_LOGIC;    
	\2a\:      IN     STD_LOGIC;    
	\2b\:      IN     STD_LOGIC;    
	\2y\:      OUT    STD_LOGIC;    
	\3a\:      IN     STD_LOGIC;    
	\3b\:      IN     STD_LOGIC;    
	\3y\:      OUT    STD_LOGIC;    
	\4a\:      IN     STD_LOGIC;    
	\4b\:      IN     STD_LOGIC;    
	\4y\:      OUT    STD_LOGIC;    
	G:         IN     STD_LOGIC;    
	\g*\:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end ds26ls32;
