// generated by newgenasym  Thu May 31 13:41:10 2012


module \lt1012s8/lt  (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    input \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    output \6 ;
    input \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
