-- generated by newgenasym Thu May 31 13:41:10 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \lt1012s8/lt\ is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       OUT    STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end \lt1012s8/lt\;
