// generated by newgenasym  Sun Oct 21 21:22:43 2012


module osc25mhz (gnd, nc, \output , vcc);
    input gnd;
    inout nc;
    output \output ;
    input vcc;


    initial
        begin
        end

endmodule
