-- generated by newgenasym Mon Jan 09 16:17:09 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity patch_probe65_40 is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end patch_probe65_40;
