-- generated by newgenasym Wed Mar 29 17:58:58 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity a3967slb is
    port (    
	DIR:       IN     STD_LOGIC;    
	\enable*\: IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	MS1:       IN     STD_LOGIC;    
	MS2:       IN     STD_LOGIC;    
	OUT1A:     OUT    STD_LOGIC;    
	OUT1B:     OUT    STD_LOGIC;    
	OUT2A:     OUT    STD_LOGIC;    
	OUT2B:     OUT    STD_LOGIC;    
	PFD:       IN     STD_LOGIC;    
	RC1:       IN     STD_LOGIC;    
	RC2:       IN     STD_LOGIC;    
	REF:       IN     STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	SENSE1:    IN     STD_LOGIC;    
	SENSE2:    IN     STD_LOGIC;    
	\sleep*\:  IN     STD_LOGIC;    
	STEP:      IN     STD_LOGIC;    
	VBB1:      IN     STD_LOGIC;    
	VBB2:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end a3967slb;
