// generated by newgenasym  Fri Jul 27 14:33:39 2012


module conn_lemo (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
