-- generated by newgenasym Fri Jul 27 14:33:39 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn_lemo is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end conn_lemo;
