-- generated by newgenasym Mon Dec 17 14:43:17 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds2411 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC);
end ds2411;
