// generated by newgenasym  Tue Jan 10 14:02:49 2017


module bav99t (anode1, anode2, cathode);
    inout anode1;
    inout anode2;
    inout cathode;


    initial
        begin
        end

endmodule
