// generated by newgenasym  Thu Jan 12 16:19:55 2017


module bav99t (anode1, anode2, cathode);
    inout anode1;
    inout anode2;
    inout cathode;


    initial
        begin
        end

endmodule
