-- generated by newgenasym Tue Jan 10 14:02:49 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bav99t is
    port (    
	ANODE1:    INOUT  STD_LOGIC;    
	ANODE2:    INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC);
end bav99t;
