// generated by newgenasym  Fri Sep 17 16:59:03 2010


module lt1761 (byp, gnd, in, out, \shdn* );
    inout byp;
    inout gnd;
    inout in;
    inout out;
    inout \shdn* ;


    initial
        begin
        end

endmodule
