-- generated by newgenasym Fri Sep 17 16:59:03 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1761 is
    port (    
	BYP:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\shdn*\:   INOUT  STD_LOGIC);
end lt1761;
