// generated by newgenasym  Wed Jan 30 20:22:22 2008


module lensadaptor (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
