-- generated by newgenasym Wed Jan 30 20:22:22 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lensadaptor is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end lensadaptor;
