// generated by newgenasym  Thu Jan 28 00:19:44 2016


module tps60502 (\1 , \10 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    input \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    input \9 ;


    initial
        begin
        end

endmodule
