-- generated by newgenasym Fri Mar 07 13:27:30 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn_mod_key is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end conn_mod_key;
