// generated by newgenasym  Mon Jun 30 12:39:38 2014


module ds15br400 (dvdd3_3, gnd, \in0+ , \in0- , \in1+ , \in1- , \in2+ , \in2- , \in3+ , \in3- ,
        \out0+ , \out0- , \out1+ , \out1- , \out2+ , \out2- , \out3+ , \out3- , pem,
        \pwdn* );
    input [5:0] dvdd3_3;
    input [1:0] gnd;
    inout \in0+ ;
    inout \in0- ;
    inout \in1+ ;
    inout \in1- ;
    inout \in2+ ;
    inout \in2- ;
    inout \in3+ ;
    inout \in3- ;
    inout \out0+ ;
    inout \out0- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out2+ ;
    inout \out2- ;
    inout \out3+ ;
    inout \out3- ;
    input pem;
    input \pwdn* ;


    initial
        begin
        end

endmodule
