-- generated by newgenasym Thu Mar 30 13:49:46 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd0805 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end csmd0805;
