-- generated by newgenasym Fri Jun 27 11:46:25 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dip8_socket_wide is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end dip8_socket_wide;
