-- generated by newgenasym Fri Mar 02 13:26:00 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0603u is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0603u;
