-- generated by newgenasym Fri Dec  4 11:22:38 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mitch_fanout_2 is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC);
end mitch_fanout_2;
