// generated by newgenasym  Mon Dec 17 16:14:12 2012


module lmh6612 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    output \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;
    output \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
