-- generated by newgenasym Wed Apr 02 15:09:02 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MMBTH10 is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end MMBTH10;
