-- generated by newgenasym Tue Aug 26 20:21:25 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r_axial is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end r_axial;
