// generated by newgenasym  Mon Feb 13 13:27:21 2012


module hv_conn2 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
