-- generated by newgenasym Mon Dec 17 16:14:12 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmh6612 is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       OUT    STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end lmh6612;
