-- generated by newgenasym Tue Sep 25 21:59:10 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity airmax150 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	B:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	C:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	D:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	E:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	F:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	G:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	H:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	I:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	J:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	K:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	L:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	M:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	N:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	O:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1));
end airmax150;
