// generated by newgenasym  Wed Mar 29 18:04:08 2006


module ls7084 (ain, bin, clk_out, dir, gnd, rbias, vcc, \x4/x1 );
    input ain;
    input bin;
    output clk_out;
    output dir;
    input gnd;
    input rbias;
    input vcc;
    input \x4/x1 ;


    initial
        begin
        end

endmodule
