-- generated by newgenasym Wed Mar 29 18:04:08 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ls7084 is
    port (    
	AIN:       IN     STD_LOGIC;    
	BIN:       IN     STD_LOGIC;    
	CLK_OUT:   OUT    STD_LOGIC;    
	DIR:       OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	RBIAS:     IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\x4/x1\:   IN     STD_LOGIC);
end ls7084;
