-- generated by newgenasym Thu Jan  6 12:49:39 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mnt_hole_106 is
    port (    
	\1\:       IN     STD_LOGIC);
end mnt_hole_106;
