// generated by newgenasym  Wed Jan 04 16:26:10 2017


module rk09l (nc1, nc2, t1, t2, w);
    inout nc1;
    inout nc2;
    inout t1;
    inout t2;
    inout w;


    initial
        begin
        end

endmodule
