-- generated by newgenasym Wed Jan 04 16:26:10 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rk09l is
    port (    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	T1:        INOUT  STD_LOGIC;    
	T2:        INOUT  STD_LOGIC;    
	W:         INOUT  STD_LOGIC);
end rk09l;
