-- generated by newgenasym Fri Mar 02 12:22:16 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsmd0805 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end rsmd0805;
