-- generated by newgenasym Fri Jun  3 17:28:14 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sc1592 is
    port (    
	CNTL:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	ILIM:      INOUT  STD_LOGIC;    
	IN_2:      INOUT  STD_LOGIC;    
	IN_3:      INOUT  STD_LOGIC;    
	OUT_5:     INOUT  STD_LOGIC;    
	OUT_6:     INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC);
end sc1592;
