-- generated by newgenasym Wed Jun 24 14:31:48 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm317t_l is
    port (    
	AN:        IN     STD_LOGIC;    
	CAT:       OUT    STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end lm317t_l;
