// generated by newgenasym  Thu Jul 26 19:04:47 2012


module lt1085 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
