// generated by newgenasym  Thu Jan  6 13:00:50 2011


module w25q64bv (clk, cs_n, di, do, gnd, hold_n, vcc, wp_n);
    input clk;
    input cs_n;
    input di;
    output do;
    input gnd;
    input hold_n;
    input vcc;
    input wp_n;


    initial
        begin
        end

endmodule
