-- generated by newgenasym Thu Jan  6 13:00:50 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity w25q64bv is
    port (    
	CLK:       IN     STD_LOGIC;    
	CS_N:      IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	DO:        OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	HOLD_N:    IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WP_N:      IN     STD_LOGIC);
end w25q64bv;
