// generated by newgenasym  Fri Jan  8 17:19:39 2010


module res_l (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
