// generated by newgenasym  Tue Dec 11 15:10:21 2012


module hfa1130 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    inout \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    output \6 ;
    input \7 ;
    input \8 ;


    initial
        begin
        end

endmodule
