-- generated by newgenasym Tue Dec 11 15:10:21 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hfa1130 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       OUT    STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end hfa1130;
