// generated by newgenasym  Fri Jun 19 17:02:53 2009


module conn4 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
