-- generated by newgenasym Fri Jun 19 17:02:53 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end conn4;
