-- generated by newgenasym Mon Mar 13 00:41:33 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \32kxtal\ is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end \32kxtal\;
