-- generated by newgenasym Wed Jan 20 21:24:11 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm2766 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end lm2766;
