// generated by newgenasym  Thu Oct 30 18:24:43 2014


module bfu730f (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
