-- generated by newgenasym Sat Mar 28 17:20:13 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TANT_CAP is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end TANT_CAP;
