-- generated by newgenasym Fri Dec  4 11:30:20 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mitch_magic is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	\out+\:    INOUT  STD_LOGIC;    
	\out-\:    INOUT  STD_LOGIC);
end mitch_magic;
