-- generated by newgenasym Wed Dec 11 16:54:46 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SOCKET8_DIP is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end SOCKET8_DIP;
