// generated by newgenasym  Tue Sep 16 15:17:48 2014


module ostoq047150 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
