// generated by newgenasym  Thu Apr 02 01:44:19 2009


module \lt1366/lt  (\+in , \+v , \-in , \-v , out);
    input \+in ;
    input \+v ;
    input \-in ;
    input \-v ;
    output out;


    initial
        begin
        end

endmodule
