-- generated by newgenasym Mon Apr  8 14:48:21 2002

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity EDGECONN36 is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN10:     INOUT  STD_LOGIC;    
	PIN11:     INOUT  STD_LOGIC;    
	PIN12:     INOUT  STD_LOGIC;    
	PIN13:     INOUT  STD_LOGIC;    
	PIN14:     INOUT  STD_LOGIC;    
	PIN15:     INOUT  STD_LOGIC;    
	PIN16:     INOUT  STD_LOGIC;    
	PIN17:     INOUT  STD_LOGIC;    
	PIN18:     INOUT  STD_LOGIC;    
	PIN19:     INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN20:     INOUT  STD_LOGIC;    
	PIN21:     INOUT  STD_LOGIC;    
	PIN22:     INOUT  STD_LOGIC;    
	PIN23:     INOUT  STD_LOGIC;    
	PIN24:     INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC;    
	PIN5:      INOUT  STD_LOGIC;    
	PIN6:      INOUT  STD_LOGIC;    
	PIN7:      INOUT  STD_LOGIC;    
	PIN8:      INOUT  STD_LOGIC;    
	PIN9:      INOUT  STD_LOGIC);
end EDGECONN36;
