-- generated by newgenasym Thu Jan 12 16:24:01 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc100el51 is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	\clk*\:    INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	Q:         INOUT  STD_LOGIC;    
	\q*\:      INOUT  STD_LOGIC;    
	R:         INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VEE:       INOUT  STD_LOGIC);
end mc100el51;
