// generated by newgenasym  Fri Dec  4 11:24:51 2009


module mitch_fanout_4 (in, out1, out2, out3, out4);
    inout in;
    inout out1;
    inout out2;
    inout out3;
    inout out4;


    initial
        begin
        end

endmodule
