// generated by newgenasym  Wed Oct 17 13:51:47 2012


module asp_channel1 (a, b, c, d, e, f, g, h, j, k);
    inout [10:1] a;
    inout [10:1] b;
    inout [10:1] c;
    inout [10:1] d;
    inout [10:1] e;
    inout [10:1] f;
    inout [10:1] g;
    inout [10:1] h;
    inout [10:1] j;
    inout [10:1] k;


    initial
        begin
        end

endmodule
