-- generated by newgenasym Fri Mar 31 11:28:57 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity csmd0603 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end csmd0603;
