-- generated by newgenasym Tue Sep 11 13:20:45 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mounthole_2mm is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end mounthole_2mm;
