-- generated by newgenasym Fri Jun 22 11:41:49 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths4130idgn is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC;    
	P5:        INOUT  STD_LOGIC;    
	P6:        INOUT  STD_LOGIC;    
	P7:        INOUT  STD_LOGIC;    
	P8:        INOUT  STD_LOGIC;    
	THERM:     INOUT  STD_LOGIC);
end ths4130idgn;
