-- generated by newgenasym Fri May 06 17:43:18 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity d_74hct244 is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\10\:      OUT    STD_LOGIC;    
	\11\:      OUT    STD_LOGIC;    
	\12\:      OUT    STD_LOGIC;    
	\13\:      IN     STD_LOGIC;    
	\14\:      OUT    STD_LOGIC;    
	\15\:      IN     STD_LOGIC;    
	\16\:      OUT    STD_LOGIC;    
	\17\:      IN     STD_LOGIC;    
	\18\:      OUT    STD_LOGIC;    
	\19\:      OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\20\:      IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       OUT    STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       OUT    STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       OUT    STD_LOGIC);
end d_74hct244;
