// generated by newgenasym  Thu Sep 12 15:49:56 2013


module opa548 (\1 , \2 , \3 , \4 , \5 , \6 , \7 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;


    initial
        begin
        end

endmodule
