-- generated by newgenasym Wed Feb 06 17:23:58 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \smt_spst_mom-sw\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end \smt_spst_mom-sw\;
