-- generated by newgenasym Tue Sep 25 17:27:45 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity THS4531 is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\10\:      OUT    STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       OUT    STD_LOGIC);
end THS4531;
