-- generated by newgenasym Fri Oct 26 01:41:36 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity em6k6 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end em6k6;
