-- generated by newgenasym Mon Sep 21 12:28:59 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity testcrap is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC;    
	P5:        INOUT  STD_LOGIC;    
	P6:        INOUT  STD_LOGIC;    
	P7:        INOUT  STD_LOGIC;    
	P8:        INOUT  STD_LOGIC);
end testcrap;
