-- generated by newgenasym Tue Oct 02 16:40:52 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity J0011D21BNL is
    port (    
	CTRX:      INOUT  STD_LOGIC;    
	CTTX:      INOUT  STD_LOGIC;    
	GANODE:    INOUT  STD_LOGIC;    
	GCATHODE:  INOUT  STD_LOGIC;    
	\rd+\:     INOUT  STD_LOGIC;    
	\rd-\:     INOUT  STD_LOGIC;    
	\td+\:     INOUT  STD_LOGIC;    
	\td-\:     INOUT  STD_LOGIC;    
	TERM1:     INOUT  STD_LOGIC;    
	TERM2:     INOUT  STD_LOGIC;    
	YANODE:    INOUT  STD_LOGIC;    
	YCATHODE:  INOUT  STD_LOGIC);
end J0011D21BNL;
