-- generated by newgenasym Fri Mar 02 12:39:29 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsm_805u is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end rsm_805u;
