-- generated by newgenasym Wed Nov 17 16:47:41 2004

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity powerreglt1185 is
    port (    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	MOUNT:     IN     STD_LOGIC;    
	REF:       IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end powerreglt1185;
