-- generated by newgenasym Fri Nov 18 14:40:27 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hfa3128 is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end hfa3128;
