-- generated by newgenasym Fri May 30 13:30:22 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ts6001 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end ts6001;
