// generated by newgenasym  Mon Oct 22 14:54:52 2012


module lt3015 (\1 , \2 , \3 , \4 , \5 , \6 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;


    initial
        begin
        end

endmodule
