-- generated by newgenasym Mon Oct 22 14:54:52 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT3015 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end LT3015;
