-- generated by newgenasym Fri Jan  8 14:07:41 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \scs20d-25mhz\ is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end \scs20d-25mhz\;
