-- generated by newgenasym Mon Sep 26 12:51:48 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MM_QUADRANT is
    port (    
	GND:       IN     STD_LOGIC);
end MM_QUADRANT;
