-- generated by newgenasym Sun Mar 30 00:51:51 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h125_plcc20a\ is
    port (    
	A:         IN     STD_LOGIC;    
	\b*\:      IN     STD_LOGIC;    
	VBB:       OUT    STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \10h125_plcc20a\;
