-- generated by newgenasym Mon Mar 31 14:51:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc08_a\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74hc08_a\;
