// generated by newgenasym  Thu Jun 07 19:06:07 2012


module opa2835_c (\1 , \10 , \2 , \3 , \4 , \5 );
    input \1 ;
    input \10 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;


    initial
        begin
        end

endmodule
