-- generated by newgenasym Thu Jun 07 19:06:07 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa2835_c is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC);
end opa2835_c;
