-- generated by newgenasym Wed Aug 08 15:32:56 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm1085 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end lm1085;
