-- generated by newgenasym Sat Mar 21 16:45:02 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt1763_33 is
    port (    
	\10 in\:   IN     STD_LOGIC;    
	\11 in\:   IN     STD_LOGIC;    
	\13 gnd/hsk\: IN     STD_LOGIC;    
	\7 gnd\:   IN     STD_LOGIC;    
	\8 shdn\:  IN     STD_LOGIC;    
	\byp 6\:   OUT    STD_LOGIC;    
	\nc 1\:    INOUT  STD_LOGIC;    
	\nc 4\:    INOUT  STD_LOGIC;    
	\nc 9\:    INOUT  STD_LOGIC;    
	NC12:      INOUT  STD_LOGIC;    
	\out 2\:   OUT    STD_LOGIC;    
	\out 3\:   OUT    STD_LOGIC;    
	\sense/adj 5\: INOUT  STD_LOGIC);
end lt1763_33;
