// generated by newgenasym  Fri Mar 08 13:08:49 2013


module ad8011 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    inout \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    inout \5 ;
    output \6 ;
    input \7 ;
    inout \8 ;


    initial
        begin
        end

endmodule
