-- generated by newgenasym Fri Mar 08 13:08:49 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AD8011 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       OUT    STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end AD8011;
