-- generated by newgenasym Fri Sep 14 12:41:38 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mounthole_4p5mm is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end mounthole_4p5mm;
