// generated by newgenasym  Fri May 14 12:36:00 2010


module ad5308 (din, gnd, ldac_n, sclk, sync_n, vdd, vouta, voutb, voutc,
        voutd, voute, voutf, voutg, vouth, vrefabcd, vrefefgh);
    input din;
    input gnd;
    input ldac_n;
    input sclk;
    input sync_n;
    input vdd;
    inout vouta;
    inout voutb;
    inout voutc;
    inout voutd;
    inout voute;
    inout voutf;
    inout voutg;
    inout vouth;
    inout vrefabcd;
    inout vrefefgh;


    initial
        begin
        end

endmodule
