-- generated by newgenasym Mon May 07 17:41:18 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bzx384-b3v3\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \bzx384-b3v3\;
