-- generated by newgenasym Thu Nov 08 13:11:07 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bas40v is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end bas40v;
