// generated by newgenasym  Thu May 31 18:38:22 2012


module opa2835_s (\10 , \5 , pd, \v_in+ , \v_in- , v_out);
    input \10 ;
    input \5 ;
    input pd;
    input \v_in+ ;
    input \v_in- ;
    output v_out;


    initial
        begin
        end

endmodule
