-- generated by newgenasym Thu May 31 18:38:22 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa2835_s is
    port (    
	\10\:      IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	PD:        IN     STD_LOGIC;    
	\v_in+\:   IN     STD_LOGIC;    
	\v_in-\:   IN     STD_LOGIC;    
	V_OUT:     OUT    STD_LOGIC);
end opa2835_s;
