// generated by newgenasym  Thu Feb  3 15:39:09 2000

`timescale 1ns/100ps

module lm337t_l (an, cat, ref);
    input an;
    output cat;
    inout ref;


    SNOVREG  inst1 (/*.REF*/ ref,
                               /*.AN*/ an,
                               /*.CAT*/ cat,
                               /*.nc4(unconnected)*/ );
endmodule
