-- generated by newgenasym Fri May 11 15:36:09 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsm0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end lsm0402;
