// generated by newgenasym  Mon Mar 31 14:51:07 2014


module \74hc08_a  (a, b, gnd, vcc, y);
    input a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
