// generated by newgenasym  Wed Jun  5 00:13:08 2002


module \10h116  (a, \b* , v, y, \y* );
    parameter    section = 1;
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] \b* ;
    output [size-1:0] y;
    output v;
    output [size-1:0] \y* ;


    initial
        begin
        end

endmodule
