// generated by newgenasym  Mon Oct 22 16:17:15 2012


module lt3080 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
