-- generated by newgenasym Wed Oct 24 12:25:58 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LMH7220 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       OUT    STD_LOGIC;    
	\4\:       OUT    STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC);
end LMH7220;
