-- generated by newgenasym Thu Mar 19 19:52:11 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa356B is
    port (    
	\2-in\:    IN     STD_LOGIC;    
	\3+in\:    IN     STD_LOGIC;    
	\4v-\:     IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	OUT6:      OUT    STD_LOGIC;    
	\v+7\:     IN     STD_LOGIC);
end opa356B;
