// generated by newgenasym  Thu Mar 26 13:44:20 2009


module lt1366_2x (\+in , \+v , \-in , \-v , out);
    input \+in ;
    input \+v ;
    input \-in ;
    input \-v ;
    output out;


    initial
        begin
        end

endmodule
