// generated by newgenasym  Tue Sep 25 21:59:10 2012


module airmax150 (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o);
    inout [10:1] a;
    inout [10:1] b;
    inout [10:1] c;
    inout [10:1] d;
    inout [10:1] e;
    inout [10:1] f;
    inout [10:1] g;
    inout [10:1] h;
    inout [10:1] i;
    inout [10:1] j;
    inout [10:1] k;
    inout [10:1] l;
    inout [10:1] m;
    inout [10:1] n;
    inout [10:1] o;


    initial
        begin
        end

endmodule
