-- generated by newgenasym Fri Feb 19 10:55:30 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity npn_2sc4617 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC);
end npn_2sc4617;
