-- generated by newgenasym Fri Aug 10 13:27:54 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths4521 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       OUT    STD_LOGIC;    
	\5\:       OUT    STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC);
end ths4521;
