-- generated by newgenasym Fri Dec 30 13:54:53 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity conn2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end conn2;
