// Generated by Part Developer

// Modified to support swift models
`timescale 1ns/100ps

module rsmd0603u (b,a);
	inout [0:0] b;
	inout [0:0] a;




	RES inst1 
		(
		.A (a[0]) ,
		.B (b[0]) 
		);



endmodule

