-- generated by newgenasym Thu Jan 12 15:21:42 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \7805_l\ is
    port (    
	GND:       INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end \7805_l\;
