-- generated by newgenasym Tue May 09 23:27:58 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ELECCAP is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ELECCAP;
