// generated by newgenasym  Thu Dec 08 12:35:41 2005


module smswitchdpdt (a, b, c, d, e, f);
    inout a;
    inout b;
    inout c;
    inout d;
    inout e;
    inout f;


    initial
        begin
        end

endmodule
