// generated by newgenasym  Tue Jun 17 15:58:40 2014


module asemplv (gnd, nc, \output+ , \output- , tristate, vcc3v3);
    input gnd;
    inout nc;
    output \output+ ;
    output \output- ;
    input tristate;
    input vcc3v3;


    initial
        begin
        end

endmodule
