-- generated by newgenasym Tue Jun 17 15:58:40 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity asemplv is
    port (    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\output+\: OUT    STD_LOGIC;    
	\output-\: OUT    STD_LOGIC;    
	TRISTATE:  IN     STD_LOGIC;    
	VCC3V3:    IN     STD_LOGIC);
end asemplv;
