-- generated by newgenasym Mon Nov 07 15:46:27 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hfa3127 is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end hfa3127;
