-- generated by newgenasym Thu Feb 04 12:33:19 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res_0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res_0402;
