-- generated by newgenasym Wed Feb 22 14:38:27 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsmd0805 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end lsmd0805;
