// generated by newgenasym  Fri Mar 12 13:54:19 2010


module sfmc40_semtec (p1, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p2, p20,
        p21, p22, p23, p24, p25, p26, p27, p28, p29, p3, p30, p31, p32,
        p33, p34, p35, p36, p37, p38, p39, p4, p40, p5, p6, p7, p8, p9);
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p13;
    inout p14;
    inout p15;
    inout p16;
    inout p17;
    inout p18;
    inout p19;
    inout p2;
    inout p20;
    inout p21;
    inout p22;
    inout p23;
    inout p24;
    inout p25;
    inout p26;
    inout p27;
    inout p28;
    inout p29;
    inout p3;
    inout p30;
    inout p31;
    inout p32;
    inout p33;
    inout p34;
    inout p35;
    inout p36;
    inout p37;
    inout p38;
    inout p39;
    inout p4;
    inout p40;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
