-- generated by newgenasym Mon Dec 02 23:42:46 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dsm_0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end dsm_0402;
