-- generated by newgenasym Mon Dec 06 11:53:49 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \pmtbase-25\ is
    port (    
	\10\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\17\:      INOUT  STD_LOGIC;    
	\19\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\20\:      INOUT  STD_LOGIC;    
	\21\:      INOUT  STD_LOGIC;    
	\24\:      INOUT  STD_LOGIC;    
	\25\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end \pmtbase-25\;
