-- generated by newgenasym Sun Oct 21 21:06:54 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CDCLVDS1102 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end CDCLVDS1102;
