-- generated by newgenasym Tue Sep 16 11:51:37 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ostoq067150 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end ostoq067150;
