// generated by newgenasym  Thu Jul 10 14:27:54 2014


module bfu710f (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
