-- generated by newgenasym Thu Mar 26 13:44:20 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LT1366_2X is
    port (    
	\+in\:     IN     STD_LOGIC;    
	\+v\:      IN     STD_LOGIC;    
	\-in\:     IN     STD_LOGIC;    
	\-v\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end LT1366_2X;
