-- generated by newgenasym Thu Jan 21 20:02:14 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mbr0520lt1 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end mbr0520lt1;
