// generated by newgenasym  Tue May 17 12:28:43 2011


module max4514_15 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    input \3 ;
    input \4 ;
    input \5 ;


    initial
        begin
        end

endmodule
