-- generated by newgenasym Tue May 17 12:28:43 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX4514_15 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC);
end MAX4514_15;
