// generated by newgenasym  Fri Nov 18 14:04:03 2005


module hfa3096 (bn, bp, cn, cp, en, ep);
    input bn;
    input bp;
    inout cn;
    inout cp;
    inout en;
    inout ep;


    initial
        begin
        end

endmodule
