// generated by newgenasym  Tue Feb 28 16:22:57 2012


module opa350 (\2#20-in , \3#20+in , \4#20v- , \5 , \6 , \7+v , \8 , out6);
    input \2#20-in ;
    input \3#20+in ;
    input \4#20v- ;
    inout \5 ;
    inout \6 ;
    input \7+v ;
    inout \8 ;
    output out6;


    initial
        begin
        end

endmodule
