-- generated by newgenasym Wed Mar 06 16:47:36 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LMH6611 is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC);
end LMH6611;
