-- generated by newgenasym Wed Apr 01 15:55:17 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ada4937-1\ is
    port (    
	\+fb\:     IN     STD_LOGIC;    
	\+in\:     IN     STD_LOGIC;    
	\+out\:    OUT    STD_LOGIC;    
	\+v1\:     IN     STD_LOGIC;    
	\+v2\:     IN     STD_LOGIC;    
	\+v3\:     IN     STD_LOGIC;    
	\+v4\:     IN     STD_LOGIC;    
	\-fb\:     IN     STD_LOGIC;    
	\-in\:     IN     STD_LOGIC;    
	\-out\:    OUT    STD_LOGIC;    
	\-v1\:     IN     STD_LOGIC;    
	\-v2\:     IN     STD_LOGIC;    
	\-v3\:     IN     STD_LOGIC;    
	\-v4\:     IN     STD_LOGIC;    
	\pd*\:     IN     STD_LOGIC;    
	VOCM:      IN     STD_LOGIC);
end \ada4937-1\;
