-- generated by newgenasym Wed Nov 07 15:28:29 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity BFT92 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end BFT92;
