-- generated by newgenasym Fri Mar 20 12:33:53 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MEC8_30CONNA is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\17\:      INOUT  STD_LOGIC;    
	\19\:      INOUT  STD_LOGIC;    
	\21\:      INOUT  STD_LOGIC;    
	\23\:      INOUT  STD_LOGIC;    
	\25\:      INOUT  STD_LOGIC;    
	\27\:      INOUT  STD_LOGIC;    
	\29\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\31\:      INOUT  STD_LOGIC;    
	\33\:      INOUT  STD_LOGIC;    
	\35\:      INOUT  STD_LOGIC;    
	\37\:      INOUT  STD_LOGIC;    
	\39\:      INOUT  STD_LOGIC;    
	\41\:      INOUT  STD_LOGIC;    
	\43\:      INOUT  STD_LOGIC;    
	\45\:      INOUT  STD_LOGIC;    
	\47\:      INOUT  STD_LOGIC;    
	\49\:      INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\51\:      INOUT  STD_LOGIC;    
	\53\:      INOUT  STD_LOGIC;    
	\55\:      INOUT  STD_LOGIC;    
	\57\:      INOUT  STD_LOGIC;    
	\59\:      INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end MEC8_30CONNA;
