// generated by newgenasym  Fri Feb 24 13:27:09 2012


module hdr4 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
