-- generated by newgenasym Fri Feb 24 13:27:09 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hdr4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end hdr4;
