// generated by newgenasym  Thu Jul 12 16:48:49 2012


module ada4940 (p1, p10, p11, p12, p13, p14, p15, p16, p17, p2, p3, p4, p5, p6, p7,
        p8, p9);
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p13;
    inout p14;
    inout p15;
    inout p16;
    inout p17;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
