-- generated by newgenasym Fri May 02 12:32:45 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end diode;
