// generated by newgenasym  Fri Oct 12 14:37:53 2012


module molex_connector (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
