-- generated by newgenasym Mon Jan 09 15:34:44 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity patch_probe is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end patch_probe;
