// generated by newgenasym  Mon May 12 12:35:29 2014


module \74lvc1g32  (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
