// Generated by Part Developer

// Modified to support swift models
`timescale 1ns/100ps

module rsmd0402 ();




	RES inst1 
		(
		.A(/* unconnected */) ,
		.B(/* unconnected */) 
		);



endmodule

