-- generated by newgenasym Mon Nov 07 15:35:37 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsmd0603 is
    port (    
	A:         IN     STD_LOGIC_VECTOR (0 DOWNTO 0);    
	B:         OUT    STD_LOGIC_VECTOR (0 DOWNTO 0));
end lsmd0603;
