-- generated by newgenasym Wed Oct 10 16:43:35 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity zum619ta is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC);
end zum619ta;
