-- generated by newgenasym Tue Jun  8 16:37:48 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity st2378e is
    port (    
	GND:       IN     STD_LOGIC;    
	IOVCC1:    INOUT  STD_LOGIC;    
	IOVCC2:    INOUT  STD_LOGIC;    
	IOVCC3:    INOUT  STD_LOGIC;    
	IOVCC4:    INOUT  STD_LOGIC;    
	IOVCC5:    INOUT  STD_LOGIC;    
	IOVCC6:    INOUT  STD_LOGIC;    
	IOVCC7:    INOUT  STD_LOGIC;    
	IOVCC8:    INOUT  STD_LOGIC;    
	IOVL1:     INOUT  STD_LOGIC;    
	IOVL2:     INOUT  STD_LOGIC;    
	IOVL3:     INOUT  STD_LOGIC;    
	IOVL4:     INOUT  STD_LOGIC;    
	IOVL5:     INOUT  STD_LOGIC;    
	IOVL6:     INOUT  STD_LOGIC;    
	IOVL7:     INOUT  STD_LOGIC;    
	IOVL8:     INOUT  STD_LOGIC;    
	OE:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VL:        IN     STD_LOGIC);
end st2378e;
