-- generated by newgenasym Tue Sep 25 17:43:24 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LTC1407B is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       OUT    STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end LTC1407B;
