// generated by newgenasym  Mon Jan 09 16:19:41 2006


module smb_coax (g1, g2, g3, g4, sig);
    input g1;
    input g2;
    input g3;
    input g4;
    inout sig;


    initial
        begin
        end

endmodule
