// generated by newgenasym  Wed Sep 20 09:54:11 2006


module bb_opa350 (\+ , \- , out, \v+ , \v- );
    inout \+ ;
    inout \- ;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
