-- generated by newgenasym Wed Sep 20 09:54:11 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bb_opa350 is
    port (    
	\+\:       INOUT  STD_LOGIC;    
	\-\:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end bb_opa350;
