// generated by newgenasym  Sat Nov 16 21:25:47 2013


module cpc7514_sp (dgnd, in1, in2, \latch1-2 , s1a, s1b, s2a, s2b, \tsd1-2 , vdd1,
        vdd2);
    inout dgnd;
    inout in1;
    inout in2;
    inout \latch1-2 ;
    inout s1a;
    inout s1b;
    inout s2a;
    inout s2b;
    inout \tsd1-2 ;
    inout vdd1;
    inout vdd2;


    initial
        begin
        end

endmodule
