-- generated by newgenasym Sat Nov 16 21:25:47 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cpc7514_sp is
    port (    
	DGND:      INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	\latch1-2\: INOUT  STD_LOGIC;    
	S1A:       INOUT  STD_LOGIC;    
	S1B:       INOUT  STD_LOGIC;    
	S2A:       INOUT  STD_LOGIC;    
	S2B:       INOUT  STD_LOGIC;    
	\tsd1-2\:  INOUT  STD_LOGIC;    
	VDD1:      INOUT  STD_LOGIC;    
	VDD2:      INOUT  STD_LOGIC);
end cpc7514_sp;
