-- generated by newgenasym Tue Jun 24 13:41:52 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max8881 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end max8881;
