-- generated by newgenasym Tue Oct 16 14:48:55 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn65lvds1 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end sn65lvds1;
