// generated by newgenasym  Fri Jun 22 11:41:49 2012


module ths4130idgn (p1, p2, p3, p4, p5, p6, p7, p8, therm);
    inout p1;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout therm;


    initial
        begin
        end

endmodule
