// generated by newgenasym  Sun Mar 30 00:51:51 2014


module \10h125_plcc20a  (a, \b* , vbb, y);
    input a;
    input \b* ;
    output vbb;
    output y;


    initial
        begin
        end

endmodule
