-- generated by newgenasym Fri Nov 18 14:05:42 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hfa3134 is
    port (    
	B:         IN     STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end hfa3134;
