// generated by newgenasym  Tue Nov 20 14:19:36 2012


module cdclvc1102 (\1 , \2 , \3 , \4 , \5 , \6 , \7 , \8 );
    input \1 ;
    input \2 ;
    output \3 ;
    input \4 ;
    inout \5 ;
    input \6 ;
    inout \7 ;
    output \8 ;


    initial
        begin
        end

endmodule
