// generated by newgenasym  Tue Mar 24 10:44:47 2009


module max4781 (\1#20x4 , \10#20b , \11#20a , \12#20x3 , \13#20x0 , \14#20x1 , \15#20x2 , \2#20x6 , \4#20x7 ,
        \5#20x5 , \6#20enable , \7#20nc , \8#20gnd , \9#20c , \vcc#2016 , \x#203 );
    input \1#20x4 ;
    input \10#20b ;
    input \11#20a ;
    input \12#20x3 ;
    input \13#20x0 ;
    input \14#20x1 ;
    input \15#20x2 ;
    input \2#20x6 ;
    input \4#20x7 ;
    input \5#20x5 ;
    input \6#20enable ;
    input \7#20nc ;
    input \8#20gnd ;
    input \9#20c ;
    input \vcc#2016 ;
    output \x#203 ;


    initial
        begin
        end

endmodule
