-- generated by newgenasym Tue Mar 24 10:44:47 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX4781 is
    port (    
	\1 x4\:    IN     STD_LOGIC;    
	\10 b\:    IN     STD_LOGIC;    
	\11 a\:    IN     STD_LOGIC;    
	\12 x3\:   IN     STD_LOGIC;    
	\13 x0\:   IN     STD_LOGIC;    
	\14 x1\:   IN     STD_LOGIC;    
	\15 x2\:   IN     STD_LOGIC;    
	\2 x6\:    IN     STD_LOGIC;    
	\4 x7\:    IN     STD_LOGIC;    
	\5 x5\:    IN     STD_LOGIC;    
	\6 enable\: IN     STD_LOGIC;    
	\7 nc\:    IN     STD_LOGIC;    
	\8 gnd\:   IN     STD_LOGIC;    
	\9 c\:     IN     STD_LOGIC;    
	\vcc 16\:  IN     STD_LOGIC;    
	\x 3\:     OUT    STD_LOGIC);
end MAX4781;
