// generated by newgenasym  Wed Apr 01 21:49:23 2009


module lt1369 (\+in , \+ina , \+inb , \+inc , \+ind , \-in , \-ina , \-inb , \-inc , \-ind , out,
        outa, outb, outc, outd, \v+ , \v- );
    input \+in ;
    input \+ina ;
    input \+inb ;
    input \+inc ;
    input \+ind ;
    input \-in ;
    input \-ina ;
    input \-inb ;
    input \-inc ;
    input \-ind ;
    output out;
    output outa;
    output outb;
    output outc;
    output outd;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
