-- generated by newgenasym Wed Jan 04 14:09:28 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bas70_04 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end bas70_04;
