-- generated by newgenasym Fri Oct 26 12:34:00 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPA2836 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC);
end OPA2836;
