// generated by newgenasym  Fri Nov 02 13:56:45 2012


module opa890 (\1 , \2 , \3 , \4 , \5 , \6 );
    output \1 ;
    input \2 ;
    input \3 ;
    input \4 ;
    input \5 ;
    input \6 ;


    initial
        begin
        end

endmodule
