-- generated by newgenasym Fri Nov 02 13:56:45 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPA890 is
    port (    
	\1\:       OUT    STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC);
end OPA890;
