-- generated by newgenasym Tue Feb 28 16:22:57 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OPA350 is
    port (    
	\2 -in\:   IN     STD_LOGIC;    
	\3 +in\:   IN     STD_LOGIC;    
	\4 v-\:    IN     STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7+v\:     IN     STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	OUT6:      OUT    STD_LOGIC);
end OPA350;
