// generated by newgenasym  Sat Mar 29 23:11:14 2014


module \10h125_plcc20b  (a, \b* , vbb, y);
    input a;
    input \b* ;
    output vbb;
    output y;


    initial
        begin
        end

endmodule
