-- generated by newgenasym Sat Mar 29 23:11:14 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \10h125_plcc20b\ is
    port (    
	A:         IN     STD_LOGIC;    
	\b*\:      IN     STD_LOGIC;    
	VBB:       OUT    STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \10h125_plcc20b\;
