-- generated by newgenasym Tue Oct 09 13:30:53 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LM4041 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end LM4041;
