-- generated by newgenasym Thu Jan 12 14:27:52 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sst211 is
    port (    
	C:         INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end sst211;
