-- generated by newgenasym Fri Oct 12 14:37:53 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity molex_connector is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end molex_connector;
