-- generated by newgenasym Wed Apr 30 12:55:18 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ferrite is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ferrite;
