// generated by newgenasym  Mon Sep 21 13:19:29 2009


module bb_opa350_v2 (inn, inp, out, \v+ , \v- );
    inout inn;
    inout inp;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
