-- generated by newgenasym Fri Jan  8 17:19:39 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res_l is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end res_l;
