-- generated by newgenasym Tue Jan 13 14:20:44 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mounthole256_92 is
    port (    
	PROBE:     INOUT  STD_LOGIC);
end mounthole256_92;
