-- generated by newgenasym Fri Oct 26 12:26:38 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity THS4524 is
    port (    
	\1\:       IN     STD_LOGIC;    
	\10\:      IN     STD_LOGIC;    
	\11\:      IN     STD_LOGIC;    
	\12\:      IN     STD_LOGIC;    
	\13\:      IN     STD_LOGIC;    
	\14\:      IN     STD_LOGIC;    
	\15\:      IN     STD_LOGIC;    
	\16\:      IN     STD_LOGIC;    
	\17\:      IN     STD_LOGIC;    
	\18\:      IN     STD_LOGIC;    
	\19\:      IN     STD_LOGIC;    
	\2\:       IN     STD_LOGIC;    
	\20\:      IN     STD_LOGIC;    
	\21\:      OUT    STD_LOGIC;    
	\22\:      OUT    STD_LOGIC;    
	\23\:      IN     STD_LOGIC;    
	\24\:      IN     STD_LOGIC;    
	\25\:      IN     STD_LOGIC;    
	\26\:      OUT    STD_LOGIC;    
	\27\:      OUT    STD_LOGIC;    
	\28\:      IN     STD_LOGIC;    
	\29\:      IN     STD_LOGIC;    
	\3\:       IN     STD_LOGIC;    
	\30\:      IN     STD_LOGIC;    
	\31\:      OUT    STD_LOGIC;    
	\32\:      OUT    STD_LOGIC;    
	\33\:      IN     STD_LOGIC;    
	\34\:      IN     STD_LOGIC;    
	\35\:      IN     STD_LOGIC;    
	\36\:      OUT    STD_LOGIC;    
	\37\:      OUT    STD_LOGIC;    
	\38\:      IN     STD_LOGIC;    
	\4\:       IN     STD_LOGIC;    
	\5\:       IN     STD_LOGIC;    
	\6\:       IN     STD_LOGIC;    
	\7\:       IN     STD_LOGIC;    
	\8\:       IN     STD_LOGIC;    
	\9\:       IN     STD_LOGIC);
end THS4524;
