-- generated by newgenasym Fri Mar 27 19:07:27 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rsocket is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end rsocket;
