// generated by newgenasym  Fri Jan 09 11:41:12 2009


module bondpad18 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 );
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \17 ;
    inout \18 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;


    initial
        begin
        end

endmodule
