-- generated by newgenasym Sun Oct 21 21:22:43 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OSC25MHZ is
    port (    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end OSC25MHZ;
