// generated by newgenasym  Fri Jun 19 15:51:52 2009


module lapas_1 (bset1_10x, bset1_1x, bset2_10x, bset2_1x, cmadj1_10x,
        cmadj2_10x, cmadj2_1x, fbk1, fbk2, fbk_3, fbk_4, g2_4,
        gnda_1, gnda_2, gnda_3, gnda_4, gnda_5, gnda_6, gnda_7,
        gnda_8, gnda_9, in1, in2, in3, in4, ina_1, ina_2, ina_3, ina_4,
        inb_1, inb_2, inb_3, inb_4, nc1, nc2, nc3, nc4, o1, o2, o3, o4,
        outa_1, outa_2, outa_3, outa_4, outb_1, outb_2, outb_3,
        outb_4, sub_1, sub_2, vcc1_1, vcc1_2, vcc2_1, vcc2_2, vcc2_3,
        vcc2_4, vdd_1, vdd_2, vdd_3, vdd_4, vfilt2, vfilt_1, vfilt_3,
        vfilt_4);
    input bset1_10x;
    input bset1_1x;
    input bset2_10x;
    input bset2_1x;
    input cmadj1_10x;
    input cmadj2_10x;
    input cmadj2_1x;
    input fbk1;
    input fbk2;
    input fbk_3;
    input fbk_4;
    input g2_4;
    inout gnda_1;
    input gnda_2;
    input gnda_3;
    input gnda_4;
    input gnda_5;
    input gnda_6;
    input gnda_7;
    input gnda_8;
    input gnda_9;
    input in1;
    input in2;
    input in3;
    input in4;
    input ina_1;
    input ina_2;
    input ina_3;
    input ina_4;
    input inb_1;
    input inb_2;
    input inb_3;
    input inb_4;
    input nc1;
    inout nc2;
    input nc3;
    input nc4;
    output o1;
    output o2;
    output o3;
    output o4;
    output outa_1;
    output outa_2;
    output outa_3;
    output outa_4;
    output outb_1;
    output outb_2;
    output outb_3;
    output outb_4;
    inout sub_1;
    input sub_2;
    input vcc1_1;
    input vcc1_2;
    input vcc2_1;
    input vcc2_2;
    input vcc2_3;
    input vcc2_4;
    input vdd_1;
    input vdd_2;
    input vdd_3;
    input vdd_4;
    input vfilt2;
    input vfilt_1;
    input vfilt_3;
    input vfilt_4;


    initial
        begin
        end

endmodule
