// generated by newgenasym  Sun Sep 21 01:28:53 2014


module minifuse_3568 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
