-- generated by newgenasym Sun Sep 21 01:28:53 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity minifuse_3568 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end minifuse_3568;
