-- generated by newgenasym Tue Mar 26 16:17:24 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX1735 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end MAX1735;
