-- generated by newgenasym Thu Apr 02 01:44:19 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \lt1366/lt\ is
    port (    
	\+in\:     IN     STD_LOGIC;    
	\+v\:      IN     STD_LOGIC;    
	\-in\:     IN     STD_LOGIC;    
	\-v\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end \lt1366/lt\;
