-- generated by newgenasym Thu Aug 26 15:47:13 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res_1206 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res_1206;
