// generated by newgenasym  Wed Oct 24 12:12:09 2012


module \5pinx  (\1 , \2 , \3 , \4 , \5 );
    input \1 ;
    input \2 ;
    output \3 ;
    input \4 ;
    input \5 ;


    initial
        begin
        end

endmodule
