-- generated by newgenasym Fri Sep 19 13:38:09 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity srr1240 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end srr1240;
