// generated by newgenasym  Mon Nov 18 16:25:53 2013


module sn74lvc1g04 (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
