// generated by newgenasym  Mon Jun  7 14:57:25 2010


module pushbutton_k5a2 (a1, a2, a3, a4, b);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout b;


    initial
        begin
        end

endmodule
