-- generated by newgenasym Mon Jun  7 14:57:25 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pushbutton_k5a2 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end pushbutton_k5a2;
