-- generated by newgenasym Fri Nov 18 14:04:03 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hfa3096 is
    port (    
	BN:        IN     STD_LOGIC;    
	BP:        IN     STD_LOGIC;    
	CN:        INOUT  STD_LOGIC;    
	CP:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC);
end hfa3096;
