-- generated by newgenasym Thu Feb 04 14:18:20 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap_0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cap_0402;
