// generated by newgenasym  Wed Mar 29 17:59:48 2006


module am26ls32 (a, b, g1, \g2* , y);
    input a;
    input b;
    input g1;
    input \g2* ;
    output y;


    initial
        begin
        end

endmodule
