// generated by newgenasym  Fri Feb 24 00:30:10 2006


module a3967slb (dir, \enable* , gnd1, gnd2, gnd3, gnd4, ms1, ms2, out1a, out1b,
        out2a, out2b, pfd, rc1, rc2, ref, \reset* , sense1, sense2,
        \sleep* , step, vbb1, vbb2, vcc);
    input dir;
    input \enable* ;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input ms1;
    input ms2;
    output out1a;
    output out1b;
    output out2a;
    output out2b;
    input pfd;
    input rc1;
    input rc2;
    input ref;
    input \reset* ;
    input sense1;
    input sense2;
    input \sleep* ;
    input step;
    input vbb1;
    input vbb2;
    input vcc;


    initial
        begin
        end

endmodule
