-- generated by newgenasym Tue Sep 16 13:25:40 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ups360e3 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end ups360e3;
