// generated by newgenasym  Mon May 12 13:48:13 2014


module \74hc32  (a, b, gnd, vcc, y);
    input a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
