-- generated by newgenasym Sun Jan 24 18:18:08 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lp2952a is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC);
end lp2952a;
