-- generated by newgenasym Mon May 12 13:58:01 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc595_b\ is
    port (    
	DS:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	QA:        OUT    STD_LOGIC;    
	QB:        OUT    STD_LOGIC;    
	QC:        OUT    STD_LOGIC;    
	QD:        OUT    STD_LOGIC;    
	QE:        OUT    STD_LOGIC;    
	QF:        OUT    STD_LOGIC;    
	QG:        OUT    STD_LOGIC;    
	QH:        OUT    STD_LOGIC;    
	QHP:       OUT    STD_LOGIC;    
	SHCP:      IN     STD_LOGIC;    
	STCP:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\|g|*\:    IN     STD_LOGIC;    
	\|srclr|*\: IN     STD_LOGIC);
end \74hc595_b\;
